In [7]:
import pandas as pd
import numpy as np

# Configuração para visualizar todas as colunas de interesse
pd.set_option('display.max_columns', None)

#cols_interesse = [
#    'AGEP_A', 'SEX_A', 'EMPWKHRS3_A', 'SLPHOURS_A', 
#    'SLPFLL_A', 'SLPSTY_A', 'PAYWORRY_A', 'K6SPD_A',
#    'ANXFREQ_A', 'ANXMED_A', 'DEPFREQ_A', 'DEPMED_A'
#]

# Leitura do arquivo CSV com os dados do censo
df_adult24 = pd.read_csv("dados/adult24.csv", ##usecols=cols_interesse## 
                 )

print(f"Dimensões iniciais: {df_adult24.shape[0]:,} linhas e {df_adult24.shape[1]} colunas.")
display(df_adult24.head(10))

Dimensões iniciais: 32,629 linhas e 630 colunas.

,RATCAT_A,INCTCFLG_A,IMPINCFLG_A,PPSU,PSTRAT,WLKLEISTC_A,WLKTRANTC_A,HISPALLP_A,RACEALLP_A,ANYDIFF_A,DISAB3_A,NUMBRN1TC_A,K6SPD_A,SCHDYMSSTC_A,AFNOW,REPWRKDYTC_A,YRSINUS_A,CITZNSTP_A,PRTNREDUCP_A,SPOUSEDUCP_A,LEGMSTAT_A,MARSTAT_A,SASPPRACE_A,SASPPHISP_A,PRTNRAGETC_A,SPOUSAGETC_A,PRTNRWKFT_A,PRTNRWRK_A,SPOUSWKFT_A,SPOUSWRK_A,SPOUSESEX_A,PRTNRSEX_A,INJWRKDYTC_A,NUMINJTC_A,SHINGYEARP_A,PROXYREL2_A,PROXYFLAG_A,HHRESPSA_FLG,PCNTADWFP1_A,PCNTADWKP1_A,FDSCAT4_A,FDSCAT3_A,EMPDYSMSS3_A,EMPLSTWOR1_A,EMPWRKFT1_A,EMPWRKLSW1_A,EMPWKHRS3_A,EMDOCCUPN2_A,EMDOCCUPN1_A,EMDINDSTN2_A,EMDINDSTN1_A,DIBAGETC_A,DIFYRSTC1_A,SMKQTNP_A,SMKQTY_A,SMKECIGST_A,SMKCIGST_A,BMICATD_A,BMICAT_A,WEIGHTLBTC_A,HEIGHTTC_A,DRKHVY12M_A,DRKSTAT_A,DRK12MYR_A,DRK12MWK_A,RETAILHC12MTC_A,URGCC12MTC_A,EMERG12MTC_A,CVDSMELCHG_A,PA18_05R_A,PA18_02R_A,MODFREQW_A,MODNR_A,MODTPR_A,MODLNR_A,MODLTPR_A,MODMIN_A,VIGNR_A,VIGTPR_A,VIGLNR_A,VIGLTPR_A,VIGFREQW_A,VIGMIN_A,STRTPR_A,STRNR_A,STRFREQW_A,PCNT18UPTC,PCNTLT18TC,LANGSPECR_A,COVER65_A,COVER_A,EXCHANGE_A,NOTCOV_A,MILSPC1R_A,OGFLG_A,OPFLG_A,CHFLG_A,MAFLG_A,PLNWRKR2_A,PLNWRKR1_A,RSNHIMISS_A,RSNHIJOB_A,MCADVR_A,PRFLG_A,PLEXCHPR1_A,PRPREM1_A,PXCHNG1_A,HICOSTR2_A,HICOSTR1_A,OTHGOV_A,OTHPUB_A,IHS_A,MILITARY_A,CHIP_A,MEDICAID_A,MEDICARE_A,PRIVATE_A,PRPLCOV1_C_A,PRPLCOV2_C_A,PLEXCHOG_A,PLEXCHOP_A,EXCHPR2_A,EXCHPR1_A,EDUCP_A,MAXEDUCP_A,PARSTAT_A,SAPARENTSC_A,MLTFAMFLG_A,OVER65FLG_A,PCNTADLT_A,PCNTKIDS_A,NUMCAN_A,COLRCAGETC_A,HDNCKAGETC_A,OTHERAGETC_A,UTERUAGETC_A,THYROAGETC_A,THROAAGETC_A,STOMAAGETC_A,SKNDKAGETC_A,SKNNMAGETC_A,SKNMAGETC_A,RECTUAGETC_A,PROSTAGETC_A,PANCRAGETC_A,OVARYAGETC_A,MOUTHAGETC_A,MELANAGETC_A,LYMPHAGETC_A,LUNGAGETC_A,LIVERAGETC_A,LEUKEAGETC_A,LARYNAGETC_A,GALLBAGETC_A,ESOPHAGETC_A,COLONAGETC_A,CERVIAGETC_A,BREASAGETC_A,BRAINAGETC_A,BONEAGETC_A,BLOODAGETC_A,BLADDAGETC_A,OTHERCANP_A,COLRCCAN_A,HDNCKCAN_A,UTERUCAN_A,THYROCAN_A,THROACAN_A,STOMACAN_A,SKNDKCAN_A,SKNNMCAN_A,SKNMCAN_A,RECTUCAN_A,PROSTCAN_A,PANCRCAN_A,OVARYCAN_A,MOUTHCAN_A,MELANCAN_A,LYMPHCAN_A,LUNGCAN_A,LIVERCAN_A,LEUKECAN_A,LARYNCAN_A,GALLBCAN_A,ESOPHCAN_A,COLONCAN_A,CERVICAN_A,BREASCAN_A,BRAINCAN_A,BONECAN_A,BLOODCAN_A,BLADDCAN_A,HISDETP_A,HISP_A,URBRRL23,REGION,INTV_QRT,SRVY_YR,SEX_A,AGEP_A,AGE65,ASTATNEW,CEVOTELC_A,CEMMETNG_A,TRANSPOR_A,HOUSECOST_A,HOUGVASST_A,HOUTENURE_A,HOUYRSLIV_A,FDSNEDAYS_A,FDSNOTEAT_A,FDSWEIGHT_A,FDSHUNGRY_A,FDSLESS_A,FDSSKIPDYS_A,FDSSKIP_A,FDSBALANCE_A,FDSLAST_A,FDSRUNOUT_A,FLUNCH12M1_A,FWIC12M_A,FSNAP30D_A,FSNAP12M_A,INCOTHR_A,INCRETIRE_A,INCWELF_A,SSISSDIDSB_A,SSISSDIBTH_A,INCSSISSDI_A,INCSSRR_A,INCINTER_A,INCWRKO_A,CEVOLUN2_A,CEVOLUN1_A,EMDWRKCAT1_A,EMDSUPER_A,EMPHEALINS_A,EMPSICKLV_A,EMPWHENWRK_A,EMPWHYNOT_A,EMPNOWRK_A,EMPLASTWK_A,SCHCURENR_A,LANGSOC_A,LANGDOC_A,LANGMED_A,LANGHM_A,NATUSBORN_A,VACAREEV_A,VAHOSP_A,VADISB_A,COMBAT_A,AFVETTRN_A,AFVET_A,EVRMARRIED_A,SPOUSEP_A,SPOUSLIV_A,MARITAL_A,ORIENT_A,TSTSMLAST_A,TSTSMHP2_A,TASTEUNW_A,TASTEFLAV_A,TASTECOMP_A,TASTEDF_A,SMELLPAR_A,SMELLPHT_A,SMELLCOMP_A,SMELLDF_A,LONELY_A,SUPPORT_A,SLPMED3_A,SLPMED2_A,SLPMED1_A,SLPMEDINTRO_A,SLPSTY_A,SLPFLL_A,SLPREST_A,SLPHOURS_A,SBURNALC_A,SBURNSCR_A,SBURNWAT_A,SBURNPHY_A,SBURNTAN_A,SBURNWRK_A,ANYSBURN1_A,SUNTAN1_A,SUNSKIN1_A,ADVACTIVE_A,PEOPLEWLK_A,WEATHERWLK_A,ANIMALWLK_A,CRIMEWLK_A,TRAFFICWLK_A,SIDEWLK_A,RELAXWLK_A,FUNWLK_A,TRANSITWLK_A,SHOPSWLK_A,ROADSWLK_A,HOMEWLK_A,WLKLEISTPD_A,WLKLEISDAY_A,WLKLEIS_A,WLKTRANTPD_A,WLKTRANDAY_A,WLKTRAN_A,DRKADVISE1_A,DRKBNG30D_A,DRKANY30D_A,DRKBNG12M_A,DRK12ANYR_A,DRKAVG12M_A,DRK12MTP_A,DRK12MN_A,DRKLIFE_A,CTLNGCAN1_A,CTLNGWHN1_A,CTSCANEV1_A,SMOKELSCR1_A,SMOKELSEV1_A,CIGAR30D_A,CIGARCUR_A,CIGAREV_A,ECIGNOW_A,ECIGEV_A,SMKTLK1_A,AVGPACKCIG_A,MENTHOLF_A,SMKQTTP_A,SMKQT12M_A,MENTHOLC_A,CIG30D_A,SMK30D_A,CIGNOW_A,SMKNOW_A,SMKAGE_A,SMKEV_A,FGELEVTRD_A,FGELNGTRD_A,FGEFRQTRD_A,TBIEVAL_A,TBILEAGUE_A,TBISPORT_A,TBIHLSBMC_A,TBILCDCMG_A,INJREDUCE_A,INJSTOPCHG_A,INJFUTWRK_A,INJSTITCH_A,INJBONES_A,INJHOSP_A,INJER_A,INJSAWDOC_A,INJCHORES_A,INJMVTYPE5_A,INJMVTYPE4_A,INJMVTYPE3_A,INJMVTYPE2_A,INJMVTYPE1_A,INJMOTOR_A,INJFALLWRK_A,INJFALLHOM_A,INJFALL_A,INJSPORTS_A,INJWORK_A,INJHOME_A,INJLIMIT_A,ANYINJURY_A,REPWRKCAUS_A,REPREDUCE_A,REPSTOPCHG_A,REPFUTWRK_A,REPSAWDOC_A,REPLIMIT_A,REPSTRAIN_A,WORTHLESS_A,EFFORT_A,HOPELESS_A,RESTLESS_A,NERVOUS_A,SAD_A,MHTHND_A,MHTHDLY_A,MHTPYNOW_A,MHTHRPY_A,MHRX_A,DEPLEVEL_A,DEPMED_A,DEPFREQ_A,ANXLEVEL_A,ANXMED_A,ANXFREQ_A,TRAVEL_A,WRKHLTHFC_A,WORKHEALTH_A,SHTHEPA_A,TDAPPREG_A,SHINGRIXFS1_A,SHINGRIXN3_A,SHINGRIX3_A,SHINGWHEN1_A,SHTSHINGL1_A,SHTPNEUNB_A,SHTPNUEV_A,CVDVAC1Y2_A,CVDVAC1M2_A,SHTCVD19NM2_A,SHTCVD191_A,FLUPREG2_A,FLUPREG_A,SHTFLUY_A,SHTFLUM_A,SHTFLU12M_A,LIVEBIRTH_A,PREGFLUYR_A,RXDG12M_A,RXDL12M_A,RXLS12M_A,RXSK12M_A,RX12M_A,HITTEST_A,HITCOMM_A,HITLOOK_A,ACCSSHOM_A,ACCSSINT_A,VIRAPP12M_A,MEDNG12M_A,MEDDL12M_A,HOSPONGT_A,USPLKIND_A,USUALPL_A,WELLVIS_A,WELLNESS_A,LASTDR_A,CVDTSTREC2_A,CVDSYMTST2_A,CVDSMREC2_A,CVDPAROS_A,CVDSYMSM2_A,LCVDACT_A,SYMPNOW1_A,LONGCOVD2_A,EVERCOVD_A,PAYWORRY_A,PAYNOBLLNW_A,PAYBLL12M_A,HINOTMYR_A,HINOTYR_A,RSNHIOTH_A,RSNHIWAIT_A,RSNHIMEET_A,RSNHICONF_A,RSNHIELIG_A,RSNHIWANT_A,RSNHICOST_A,HISTOPELIG_A,HISTOPCOST_A,HISTOPAGE_A,HISTOPMISS_A,HISTOPJOB_A,HILASTMY_A,HILAST_A,MILSPC3_A,MILSPC2_A,MILSPC1_A,OGHDHP_A,OGDEDUC_A,OGPREM_A,OGXCHNG_A,OPHDHP_A,OPDEDUC_A,OPPREM_A,OPXCHNG_A,CHHDHP_A,CHDEDUC_A,CHPREM_A,CHXCHNG_A,PRVSCOV2_A,PRVSCOV1_A,PRDNCOV2_A,PRDNCOV1_A,PRRXCOV2_A,PRRXCOV1_A,HSAHRA2_A,HSAHRA1_A,PRHDHP2_A,PRHDHP1_A,PRDEDUC2_A,PRDEDUC1_A,PLN2PAY6_A,PLN2PAY5_A,PLN2PAY4_A,PLN2PAY3_A,PLN2PAY2_A,PLN2PAY1_A,PLN1PAY6_A,PLN1PAY5_A,PLN1PAY4_A,PLN1PAY3_A,PLN1PAY2_A,PLN1PAY1_A,PLNEXCHG2_A,PLNEXCHG1_A,PRPOLH2_A,PRPOLH1_A,PRPLCOV2_A,PRPLCOV1_A,POLHLD2_A,POLHLD1_A,MAHDHP_A,MADEDUC_A,MAPREM_A,MAXCHNG_A,MCPARTD_A,MCVSCOV_A,MCDNCOV_A,MCHMO_A,MCCHOICE_A,MCPART_A,SINCOVRX_A,SINCOVVS_A,SINCOVDE_A,MCAIDPRB_A,MCAREPRB_A,HIKIND10_A,HIKIND09_A,HIKIND08_A,HIKIND07_A,HIKIND06_A,HIKIND05_A,HIKIND04_A,HIKIND03_A,HIKIND02_A,HIKIND01_A,HICOV_A,DEVDONSET_A,SOCWRKLIM_A,SOCSCLPAR_A,SOCERRNDS_A,UPPOBJCT_A,UPPRAISE_A,UPPSLFCR_A,COGAMTDFF_A,COGFRQDFF_A,COGTYPEDFF_A,COGMEMDFF_A,COMUSESL_A,COMDIFF_A,EQSTEPS_A,EQWLK13M_A,EQWLK100_A,NOEQSTEPS_A,NOEQWLK13M_A,NOEQWLK100_A,PERASST_A,WCHAIR_A,CANEWLKR_A,STEPS_A,WLK13M_A,WLK100_A,EQUIP_A,DIFF_A,HEARNYRM_A,HEARQTRM_A,HEARINGDF_A,HEARAIDFR_A,HEARAID_A,VISIONDF_A,WEARGLSS_A,PREGNOW_A,DXSKIN_A,CURSKIN_A,DXFOOD_A,CURFOOD_A,DXRESP_A,CURRESP_A,HLTHCOND_A,MEDRXTRT_A,DRYMTH12M_A,COLDFLU12M_A,CFSNOW_A,CFSEV_A,PSOREV_A,ULCCOLEV_A,CROHNSEV_A,LIVEREV_A,HEPEV_A,KIDWEAKEV_A,DEPEV_A,ANXEV_A,DEMENEV_A,ARTHEV_A,COPDEV_A,DIBTYPE_A,DIBGLP_A,DIBINSSTYR_A,DIBINSSTOP_A,DIBINSTIME_A,DIBINS_A,DIBPILL_A,DIBEV_A,GESDIB_A,PREDIB_A,CANEV_A,ASER12M_A,ASAT12M_A,ASTILL_A,ASEV_A,STREV_A,MIEV_A,ANGEV_A,CHDEV_A,CHLMED_A,CHL12M_A,CHLEV_A,HYPMED_A,HYP12M_A,HYPDIF_A,HYPEV_A,LSATIS4_A,PHSTAT_A,HHSTAT_A,INTV_MON,RECTYPE,IMPNUM_A,AVGNUMCIG_A,WTFA_A,HHX,POVRATTC_A
0,9,0,2,2,122,NaN,NaN,2,1,2,2,NaN,2,NaN,2.0,NaN,NaN,1,NaN,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,1,1,1,1,0.0,NaN,1.0,1,40.0,1.0,4.0,1.0,2.0,NaN,NaN,3.0,3.0,3,3,3,3,165,67,NaN,1,NaN,NaN,0,0,0,1.0,3,3,6,6,2,30.0,1.0,30.0,0,0,NaN,NaN,94,NaN,0,0,94,1,2,NaN,NaN,4.0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,3,3,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,5,5.0,1,1,2,0,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4,3,1,2024,1,49,NaN,1,2,2,2,2,NaN,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,2.0,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2,1,2.0,2,5.0,1.0,2.0,2.0,NaN,NaN,NaN,1,2,NaN,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,NaN,1.0,2.0,1,2,NaN,2,2,3,3,1,2,2,3,1,3,1,1,1,1,1,1,1,3,8,NaN,NaN,NaN,NaN,NaN,NaN,2,2,5,2,4,3,2,2,2,2,2,2,2,2,2,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2.0,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,3.0,23.0,1,3.0,1.0,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5,5,4,4,5,2,2,NaN,2,2.0,NaN,2,5,3.0,2,4,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,NaN,NaN,2,2.0,2.0,2.0,1.0,1,2,2,2,2,NaN,2,NaN,1.0,5,NaN,2.0,1.0,1.0,1.0,NaN,NaN,2.0,1,2,NaN,2,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2.0,NaN,1,2,2,2,2,2,2,2,2,2,2,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1.0,1.0,1,NaN,2,1,2,NaN,NaN,2,NaN,2,NaN,2,2,2,2,2,NaN,2,2,2,2,2,2,2,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,2,2,2,2,NaN,NaN,2,NaN,NaN,NaN,2,1,1,1,1,10,1,30,5780.565,H067658,2.82
1,8,0,0,2,122,20.0,NaN,2,1,2,2,NaN,2,NaN,2.0,NaN,4.0,1,NaN,NaN,5,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,1,1,1,1,0.0,NaN,1.0,1,40.0,21.0,86.0,5.0,11.0,NaN,NaN,20.0,20.0,3,3,3,3,180,70,NaN,1,NaN,NaN,2,2,2,NaN,1,1,94,0,0,NaN,NaN,NaN,0,0,NaN,NaN,94,NaN,0,0,94,1,0,2.0,NaN,1.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2400.0,3,3,2,3,3,3,3,1,NaN,NaN,NaN,NaN,NaN,1.0,5,5.0,3,3,2,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4,3,1,2024,1,53,NaN,1,2,2,1,2,2.0,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2,1,2.0,2,1.0,2.0,1.0,1.0,NaN,NaN,NaN,1,2,1.0,1.0,1.0,1,2,NaN,NaN,NaN,NaN,NaN,2,1.0,NaN,NaN,3,2,NaN,2,2,3,3,1,2,2,3,1,5,5,1,1,1,1,1,1,3,8,NaN,NaN,NaN,NaN,NaN,NaN,2,6,6,2,1,3,2,2,2,1,1,2,2,1,1,3.0,1.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2.0,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,3.0,4.0,NaN,NaN,NaN,NaN,NaN,3.0,10.0,1,NaN,NaN,1,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5,5,5,5,5,2,2,NaN,2,2.0,NaN,2,5,NaN,2,5,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,NaN,NaN,2,2.0,2.0,2.0,1,2.0,2.0,2.0,1.0,1,2,2,2,2,1.0,1,NaN,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,NaN,NaN,2,2,2,2,2,2,2,2,2,1,1,NaN,2,1,1,1,1,1,NaN,NaN,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1.0,1.0,1,NaN,2,1,2,NaN,NaN,2,NaN,2,NaN,2,2,2,2,2,NaN,2,2,2,2,2,2,2,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,2,2,2,2,NaN,NaN,2,1.0,1.0,1.0,1,2,2,1,1,10,1,20,3994.244,H076577,2.01
2,7,0,0,2,122,30.0,NaN,2,1,1,2,NaN,2,NaN,NaN,NaN,NaN,1,NaN,5.0,3,1,1.0,1.0,NaN,69.0,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,1.0,0,0,1,1,NaN,3.0,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,22.0,3,3,4,4,215,68,2.0,7,104.0,2.0,0,0,0,2.0,1,1,94,0,0,NaN,NaN,NaN,0,0,NaN,NaN,94,NaN,0,0,94,2,0,NaN,3.0,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,3,3,3,1,3,NaN,NaN,NaN,NaN,NaN,NaN,5,5.0,3,3,2,1,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4,3,1,2024,1,82,NaN,1,2,2,2,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,1.0,2,2,2.0,2,NaN,NaN,NaN,NaN,3.0,4.0,2.0,2,2,NaN,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,1.0,1,2,NaN,2,2,3,3,1,2,2,3,1,5,1,1,1,1,1,1,2,4,8,NaN,NaN,NaN,NaN,NaN,NaN,2,6,6,1,4,3,1,2,2,2,2,2,2,2,1,1.0,2.0,2.0,1.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,NaN,3.0,1.0,2.0,1,2.0,2.0,1.0,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,3.0,9.0,1,3.0,1.0,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5,5,5,5,5,2,2,NaN,2,2.0,NaN,2,5,NaN,2,5,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2,2020.0,4.0,1.0,1,NaN,NaN,2023.0,10.0,1,NaN,NaN,2,2.0,2.0,2.0,1,NaN,NaN,NaN,NaN,2,2,2,2,2,1.0,1,1.0,2.0,1,NaN,2.0,NaN,2.0,2.0,NaN,NaN,2.0,1,3,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,3.0,2,2,2,NaN,NaN,2,2,2,2,2,2,2,2,1,2,1,NaN,2,1,1,1,1,1,NaN,NaN,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2,2,1.0,1.0,1,2.0,1,1,2,NaN,NaN,2,NaN,2,2.0,1,2,2,2,1,NaN,2,2,2,2,2,2,2,2,2,2,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,2,1,2,1,NaN,NaN,2,2.0,2.0,1.0,1,1,2,1,1,10,1,20,6636.755,H019335,1.90
3,12,0,0,2,122,10.0,NaN,2,1,1,2,2.0,2,NaN,2.0,NaN,NaN,1,NaN,10.0,3,1,1.0,1.0,NaN,34.0,NaN,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,2,1,0.0,NaN,1.0,1,40.0,21.0,86.0,3.0,9.0,NaN,NaN,15.0,15.0,3,3,3,3,200,72,2.0,6,52.0,1.0,0,0,0,NaN,1,2,1,1,2,10.0,1.0,10.0,6,4,15.0,1.0,0,15.0,3,1,0,2,1,NaN,NaN,1.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.0,3,3,2,3,3,3,3,1,NaN,NaN,NaN,NaN,NaN,1.0,4,10.0,1,1,2,0,2,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4,3,1,2024,1,42,NaN,1,2,2,2,2,NaN,1,2,NaN,NaN,2.0,2.0,2.0,NaN,2.0,3,2,3,2.0,2.0,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1,1,2.0,2,1.0,2.0,1.0,1.0,NaN,NaN,NaN,1,2,NaN,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,1.0,1,2,NaN,2,2,3,3,1,2,2,2,1,4,3,1,1,1,1,2,1,2,8,2.0,1.0,1.0,2.0,2.0,1.0,1,4,1,2,4,2,2,2,1,2,1,2,2,2,2,1.0,1.0,2.0,1.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,NaN,1.0,1.0,1.0,1,NaN,NaN,2.0,3.0,1,0.0,2.0,1,NaN,2,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,3.0,15.0,1,NaN,NaN,1,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,3,5,5,4,5,2,2,NaN,2,2.0,1.0,2,4,1.0,2,3,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2021.0,9.0,2.0,1,NaN,NaN,2023.0,9.0,1,NaN,NaN,2,2.0,2.0,2.0,1,2.0,2.0,1.0,1.0,1,2,2,2,2,5.0,1,NaN,1.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,1.0,NaN,1.0,NaN,9.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,1,NaN,NaN,2,2,2,2,2,2,2,2,2,1,1,NaN,2,1,1,1,1,1,NaN,NaN,2.0,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,2.0,1.0,1,NaN,2,1,1,NaN,NaN,2,NaN,2,2.0,1,2,2,2,2,NaN,2,2,2,2,2,2,2,2,1,2,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,2,2,2,2,NaN,NaN,2,NaN,NaN,NaN,2,2,3,1,1,10,1,01,13767.420,H012701,4.48
4,14,0,0,1,115,NaN,NaN,3,2,1,2,2.0,2,NaN,2.0,NaN,NaN,1,NaN,NaN,4,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,2,2,1,1,10.0,NaN,1.0,1,45.0,6.0,17.0,19.0,76.0,NaN,NaN,NaN,NaN,3,4,3,3,145,59,2.0,6,48.0,1.0,0,4,1,NaN,4,3,3,3,2,30.0,1.0,30.0,1,2,30.0,1.0,1,30.0,2,2,2,2,0,NaN,NaN,1.0,2.0,2,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99999.0,99999.0,3,3,2,3,3,3,3,1,NaN,NaN,NaN,NaN,2.0,2.0,9,9.0,3,3,2,0,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,2,3,1,2024,2,38,NaN,1,1,1,2,2,2.0,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,2.0,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2,1,NaN,1,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1,2,NaN,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,2.0,NaN,NaN,3,2,NaN,2,2,3,3,1,2,2,3,1,4,2,1,1,1,1,1,2,3,8,2.0,1.0,1.0,2.0,NaN,2.0,1,5,4,2,4,3,1,2,2,2,1,1,1,1,1,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,4.0,1,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,1.0,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5,5,4,4,5,2,2,NaN,2,NaN,1.0,2,4,3.0,1,4,1,2.0,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2023.0,12.0,3.0,1,NaN,NaN,2023.0,12.0,1,2.0,2.0,1,2.0,2.0,2.0,1,1.0,1.0,1.0,1.0,1,1,2,2,2,1.0,1,1.0,2.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,NaN,NaN,2,2,2,2,2,2,2,2,2,1,1,NaN,2,1,1,1,1,1,NaN,NaN,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1.0,1.0,1,NaN,2,2,1,2.0,NaN,2,NaN,2,1.0,1,2,2,2,2,NaN,2,2,2,2,2,2,2,1,1,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2,2,1.0,1.0,1.0,1,2,2,2,2,NaN,NaN,2,NaN,NaN,NaN,2,2,3,1,1,10,1,NaN,18880.030,H049678,6.37
5,11,0,1,1,115,NaN,NaN,3,2,1,2,NaN,2,NaN,2.0,NaN,NaN,1,NaN,NaN,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,1,1,1,1,NaN,2.0,NaN,2,NaN,NaN,NaN,NaN,NaN,65.0,11.0,NaN,NaN,3,4,3,3,153,65,NaN,1,NaN,NaN,0,0,0,NaN,1,1,94,0,0,NaN,NaN,NaN,0,0,NaN,NaN,94,NaN,0,0,94,2,0,NaN,1.0,NaN,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,3,3,2,3,3,3,1,1,NaN,NaN,NaN,NaN,NaN,2.0,6,6.0,3,3,2,1,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,2,3,1,2024,2,76,NaN,1,1,2,2,2,NaN,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,1.0,2,1,2.0,2,NaN,NaN,NaN,NaN,2.0,3.0,2.0,2,2,NaN,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,1.0,NaN,NaN,3,2,NaN,2,2,3,3,1,2,2,3,1,4,3,1,1,2,1,3,3,2,8,NaN,NaN,NaN,NaN,NaN,NaN,2,5,6,1,3,4,2,2,1,2,2,2,1,2,2,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,4.0,1.0,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,1,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5,5,4,5,5,2,2,NaN,2,2.0,NaN,2,5,1.0,2,4,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2,2022.0,6.0,2.0,1,NaN,NaN,NaN,NaN,2,NaN,NaN,2,2.0,2.0,2.0,1,2.0,2.0,1.0,1.0,1,2,2,2,2,1.0,1,NaN,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,3.0,2,2,2,NaN,NaN,2,2,2,2,2,2,2,2,1,1,1,NaN,2,1,1,1,1,1,1.0,1.0,1.0,2,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2,2,1.0,1.0,1,NaN,2,1,1,NaN,NaN,2,NaN,2,NaN,2,2,2,2,2,NaN,2,2,2,2,2,2,2,2,2,2,2,2,2.0,2.0,NaN,2.0,4.0,1.0,2.0,1,2.0,1,2,NaN,NaN,NaN,2,2,2,2,2,1.0,2.0,1,1.0,2.0,1.0,1,1,3,1,1,10,1,NaN,13755.497,H060942,3.80

In [ ]:
# Tabela 1: Contagem de nulos e tipos de dados
tab_nulos = pd.DataFrame({ # cria uma nova tabela com informações sobre valores nulos e tipos de dados
    'Valores_Nulos': df_adult24.isnull().sum(),
    'Porcentagem_Nulos (%)': (df_adult24.isnull().sum() / len(df_adult24) * 100).round(2),
    'Tipo_Dado': df_adult24.dtypes
})
print("=== TABELA 1: DIAGNÓSTICO DE VALORES AUSENTES ===")
display(tab_nulos)

# Tabela 2: Resumo estatístico das variáveis contínuas (Idade, Sono e Horas Trabalhadas)
#print("\n=== TABELA 2: RESUMO ESTATÍSTICO DAS VARIÁVEIS NUMÉRICAS ===")
#display(df_adult24[['AGEP_A', 'SLPHOURS_A', 'EMPWKHRS3_A']].describe().T.round(2))

=== TABELA 1: DIAGNÓSTICO DE VALORES AUSENTES ===

             Valores_Nulos  Porcentagem_Nulos (%) Tipo_Dado
RATCAT_A                 0                   0.00     int64
INCTCFLG_A               0                   0.00     int64
IMPINCFLG_A              0                   0.00     int64
PPSU                     0                   0.00     int64
PSTRAT                   0                   0.00     int64
...                    ...                    ...       ...
IMPNUM_A                 0                   0.00     int64
AVGNUMCIG_A          21104                  64.68       str
WTFA_A                   0                   0.00   float64
HHX                      0                   0.00       str
POVRATTC_A               0                   0.00   float64

[630 rows x 3 columns]

=== TABELA 2: RESUMO ESTATÍSTICO DAS VARIÁVEIS NUMÉRICAS ===

               count   mean    std   min   25%   50%   75%   max
AGEP_A       32629.0  53.45  18.67  18.0  37.0  55.0  69.0  99.0
SLPHOURS_A   32629.0  10.26  16.66   1.0   6.0   7.0   8.0  99.0
EMPWKHRS3_A  18011.0  39.94  13.74   1.0  38.0  40.0  45.0  99.0

Temos apenas 3 variáveis numéricas

Idade

Horas de sono

Horas trabalhadas por semana

In [ ]:
# Tabela 3: Distribuição de códigos em variáveis-chave
#cols_para_checar = ['SEX_A', 'SLPFLL_A', 'PAYWORRY_A', 'ANXMED_A', 'DEPMED_A', 'ANXFREQ_A']

#tab_codigos = pd.DataFrame({col: df_adult24[col].value_counts().sort_index() for col in cols_para_checar}).fillna(0).astype(int)
#print("=== TABELA 3: CONTAGEM DE CÓDIGOS ORIGINAIS DO QUESTIONÁRIO ===")
#display(tab_codigos)

#Não faz sentido criar uma tabela de códigos pois cada valor significa uma coisa diferente, e não há uma relação entre eles.

In [ ]:
# 1. Filtros de sanitização
#df = df[df['SLPHOURS_A'] <= 24].copy()
#df = df[df['SEX_A'].isin([1, 2])].copy()
#
#for col in ['SLPFLL_A', 'SLPSTY_A', 'PAYWORRY_A', 'ANXMED_A', 'DEPMED_A']:
#    df = df[df[col].isin([1, 2, 3, 4])].copy()
#
#for col in ['ANXFREQ_A', 'DEPFREQ_A']:
#    df = df[df[col].isin([1, 2, 3, 4, 5])].copy()
#
# 2. Criação do Target e Rótulos Semânticos
#df['target_medicacao'] = ((df['ANXMED_A'] == 1) | (df['DEPMED_A'] == 1)).astype(int)
#df['STATUS_MEDICACAO'] = df['target_medicacao'].map({0: 'Não Toma', 1: 'Toma Medicamento'})
#df['SEXO_LABEL'] = df['SEX_A'].map({1: 'Masculino', 2: 'Feminino'})
#df['INSÔNIA_INICIAL'] = df['SLPFLL_A'].map({1: '1. Nunca', 2: '2. Raramente', 3: '3. Alguns dias', 4: '4. Quase sempre'})
#df['ESTRESSE_CONTAS'] = df['PAYWORRY_A'].map({1: '1. Muito Preocupado', 2: '2. Moderado', 3: '3. Pouco', 4: '4. Nada'})
#df['FREQ_ANSIEDADE'] = df['ANXFREQ_A'].map({1: '1. Diária', 2: '2. Semanal', 3: '3. Mensal', 4: '4. Rara', 5: '5. Nunca'})

#print(f"Dimensões após limpeza: {df.shape[0]:,} linhas válidas.")
#display(df[['AGEP_A', 'SEXO_LABEL', 'SLPHOURS_A', 'INSÔNIA_INICIAL', 'ESTRESSE_CONTAS', 'FREQ_ANSIEDADE', 'STATUS_MEDICACAO']].head(10))

Dimensões após limpeza: 31,187 linhas válidas.

,AGEP_A,SEXO_LABEL,SLPHOURS_A,INSÔNIA_INICIAL,ESTRESSE_CONTAS,FREQ_ANSIEDADE,STATUS_MEDICACAO
0,49,Masculino,8,1. Nunca,2. Moderado,4. Rara,Não Toma
1,53,Masculino,8,1. Nunca,3. Pouco,5. Nunca,Não Toma
2,82,Masculino,8,2. Raramente,3. Pouco,5. Nunca,Não Toma
3,42,Masculino,8,1. Nunca,1. Muito Preocupado,3. Mensal,Não Toma
4,38,Feminino,8,2. Raramente,3. Pouco,4. Rara,Toma Medicamento
5,76,Feminino,8,3. Alguns dias,3. Pouco,4. Rara,Não Toma
6,48,Masculino,8,1. Nunca,2. Moderado,5. Nunca,Não Toma
7,51,Masculino,6,1. Nunca,1. Muito Preocupado,4. Rara,Toma Medicamento
9,39,Masculino,8,2. Raramente,3. Pouco,4. Rara,Não Toma
10,63,Masculino,6,1. Nunca,1. Muito Preocupado,3. Mensal,Não Toma

In [ ]:
#Nova sanitização: Traduzir todas as colunas
df_adult24 = df_adult24.rename(columns={"RECTYPE": "Tipo_Registro",
"SRVY_YR": "Ano_Pesquisa",
"HHX": "ID_Domicilio",
"WTFA_A": "Peso_Amostral",
"URBRRL23": "Area_Urbana",
"REGION": "Região",
"PPSU": "Pseudo_Primary_Sampling_Unit",
"PSTRAT": "Pseudo_Stratum",
"HHRESPSA_FLG": "Flag_Respondente_Domicilio",
"PROXYFLAG_A": "Flag_Responde_Proxy",
"PROXYREL2_A": "Parentesco_Responde_Proxy",
"INTV_QRT": "Trimestre_Entrevista",
"INTV_MON": "Mes_Entrevista",
"HHSTAT_A": "Indica_pessoa_é_o_Adulto_da_Amostra",
"ASTATNEW": "Entrevista_Completude",
"AFNOW": "Trabalha_militar",
"PCNT18UPTC": "Quantos_maiores_18_casa",
"PCNTLT18TC": "Quantos_menores_18_casa",
"SEX_A": "Sexo",
"AGE65": "Quantos_adultos_com_65+_casa",
"AGEP_A": "Idade",
"HISP_A": "Origem_Hispanica",
"HISDETP_A": "Mexico_Origem_Hispanica",
"RACEALLP_A": "Raca_Etnia",
"HISPALLP_A": "Composicao_Hispanica_Raca_Etnia",
"EDUCP_A": "Educacao",
"PCNTADLT_A": "Quantos_adultos_casa",
"PCNTKIDS_A": "Quantos_criancas_casa",
"OVER65FLG_A": "Flag_Adulto_65+_casa",
"MLTFAMFLG_A": "Flag_Multifamiliar",
"MAXEDUCP_A": "Educacao_Maxima_casa",
"PHSTAT_A": "Saude_Fisica",
"LSATIS4_A": "Satisfacao_Vida",
"HYPEV_A": "Hipertensao_Diagnostico",
"HYPDIF_A": "Hipertensao_Diagnostico_Dois_ou_mais_medicos",
"HYP12M_A": "Hipertensao_12_meses",
"HYPMED_A": "Hipertensao_Medicacao",
"CHLEV_A": "Colesterol_Diagnostico",
"CHL12M_A": "Colesterol_12_meses",
"CHLMED_A": "Colesterol_Medicacao",
"CHDEV_A": "Doenca_Cardiovascular_Diagnostico",
"ANGEV_A": "Teve_angina",
"MIEV_A": "Teve_infarto",
"STREV_A": "Teve_AVC",
"ASEV_A": "Teve_Asma",
"ASTILL_A": "Asma_Ativa",
"ASAT12M_A": "Asma_12_meses",
"ASER12M_A": "Ermegencia_asma_12_meses",
"CANEV_A": "Teve_cancer",
"BLADDCAN_A": "Teve_cancer_bexiga",
"BLADDAGETC_A": "Idade_diagnostico_cancer_bexiga",
"BLOODCAN_A": "Teve_cancer_sangue",
"BLOODAGETC_A": "Idade_diagnostico_cancer_sangue",
"BONECAN_A": "Teve_cancer_osso",
"BONEAGETC_A": "Idade_diagnostico_cancer_osso",
"BRAINCAN_A": "Teve_cancer_cerebro",
"BRAINAGETC_A": "Idade_diagnostico_cancer_cerebro",
"BREASCAN_A": "Teve_cancer_mama",
"BREASAGETC_A": "Idade_diagnostico_cancer_mama",
"CERVICAN_A": "Teve_cancer_cervix",
"CERVIAGETC_A": "Idade_diagnostico_cancer_cervix",
"COLONCAN_A": "Teve_cancer_colon",
"COLONAGETC_A": "Idade_diagnostico_cancer_colon",
"ESOPHCAN_A": "Teve_cancer_esofago",
"ESOPHAGETC_A": "Idade_diagnostico_cancer_esofago",
"GALLBCAN_A": "Teve_cancer_vesicula_biliar",
"GALLBAGETC_A": "Idade_diagnostico_cancer_vesicula_biliar",
"LARYNCAN_A": "Teve_cancer_laringe",
"LARYNAGETC_A": "Idade_diagnostico_cancer_laringe",
"LEUKECAN_A": "Teve_cancer_leucemia",
"LEUKEAGETC_A": "Idade_diagnostico_cancer_leucemia",
"LIVERCAN_A": "Teve_cancer_figado",
"LIVERAGETC_A": "Idade_diagnostico_cancer_figado",
"LUNGCAN_A": "Teve_cancer_pulmao",
"LUNGAGETC_A": "Idade_diagnostico_cancer_pulmao",
"LYMPHCAN_A": "Teve_cancer_linfoma",
"LYMPHAGETC_A": "Idade_diagnostico_cancer_linfoma",
"MELANCAN_A": "Teve_cancer_melanoma",
"MELANAGETC_A": "Idade_diagnostico_cancer_melanoma",
"MOUTHCAN_A": "Teve_cancer_boca",
"MOUTHAGETC_A": "Idade_diagnostico_cancer_boca",
"OVARYCAN_A": "Teve_cancer_ovario",
"OVARYAGETC_A": "Idade_diagnostico_cancer_ovario",
"PANCRCAN_A": "Teve_cancer_pancreas",
"PANCRAGETC_A": "Idade_diagnostico_cancer_pancreas",
"PROSTCAN_A": "Teve_cancer_prostata",
"PROSTAGETC_A": "Idade_diagnostico_cancer_prostata",
"RECTUCAN_A": "Teve_cancer_reto",
"RECTUAGETC_A": "Idade_diagnostico_cancer_reto",
"SKNMCAN_A": "Teve_cancer_pele_melanoma",
"SKNMAGETC_A": "Idade_diagnostico_cancer_pele_melanoma",
"SKNNMCAN_A": "Teve_cancer_pele_nao_melanoma",
"SKNNMAGETC_A": "Idade_diagnostico_cancer_pele_nao_melanoma",
"SKNDKCAN_A": "Teve_cancer_pele_desconhecido",
"SKNDKAGETC_A": "Idade_diagnostico_cancer_pele_desconhecido",
"STOMACAN_A": "Teve_cancer_estomago",
"STOMAAGETC_A": "Idade_diagnostico_cancer_estomago",
"THROACAN_A": "Teve_cancer_faringe",
"THROAAGETC_A": "Idade_diagnostico_cancer_faringe",
"THYROCAN_A": "Teve_cancer_tireoide",
"THYROAGETC_A": "Idade_diagnostico_cancer_tireoide",
"UTERUCAN_A": "Teve_cancer_utero",
"UTERUAGETC_A": "Idade_diagnostico_cancer_utero",
"HDNCKCAN_A": "Teve_cancer_cabeca_pescoco",
"HDNCKAGETC_A": "Idade_diagnostico_cancer_cabeca_pescoco",
"COLRCCAN_A": "Teve_cancer_colorretal",
"COLRCAGETC_A": "Idade_diagnostico_cancer_colorretal",
"OTHERCANP_A": "Teve_outro_cancer",
"OTHERAGETC_A": "Idade_diagnostico_outro_cancer",
"NUMCAN_A": "Numero_total_cancer",
"PREDIB_A": "Prediabetes_Diagnostico",
"GESDIB_A": "Gestacional_Diabetes_Diagnostico",
"DIBEV_A": "Diabetes_Diagnostico",
"DIB12M_A": "Diabetes_12_meses",
"DIFYRSTC1_A": "Idade_diagnostico_diabetes",
"DIBPILL_A": "Diabetes_Medicacao_Pilula",
"DIBINS_A": "Diabetes_Medicacao_Insulina",
"DIBINSTIME_A": "Diabetes_Medicacao_Insulina_Tempo",
"DIBINSSTOP_A": "Diabetes_Medicacao_Insulina_Parou",
"DIBINSSTYR_A": "Diabetes_Medicacao_Insulina_Parou_Ano",
"DIBGLP_A": "Diabetes_Medicacao_Injetavel",
"DIBTYPE_A": "Diabetes_Tipo",
"COPDEV_A": "Doenca_Pulmonar_Obstrutiva_Cronica_Diagnostico",
"ARTHEV_A": "Artrite_Diagnostico",
"DEMENEV_A": "Demencia_Diagnostico",
"ANXEV_A": "Ansiedade_Diagnostico",
"DEPEV_A": "Depressao_Diagnostico",
"KIDWEAKEV_A": "Doenca_Rim_Diagnostico",
"HEPEV_A": "Hepatite_Diagnostico",
"LIVEREV_A": "Doenca_Figado_Diagnostico",
"CROHNSEV_A": "Doenca_Crohn_Diagnostico",
"ULCCOLEV_A": "Colite_Ulcerativa_Diagnostico",
"PSOREV_A": "Psoriase_Diagnostico",
"CFSEV_A" : "Fatiga_Cronica_Diagnostico",
"CFSNOW_A": "Fatiga_Cronica_Hoje",
"COLDFLU12M_A": "Resfriado_Gripe_12_meses_mais_1_mes",
"DRYMTH12M_A": "Boca_Seca_12_meses",
"MEDRXTRT_A": "Tratamento_Imunosupressor",
"HLTHCOND_A": "Condicao_Imunocomprometida",
"CURRESP_A": "Alergia_Respiratoria",
"DXRESP_A": "Alergia_Respiratoria_Diagnostico",
"CURFOOD_A": "Alergia_Alimentar",
"DXFOOD_A": "Alergia_Alimentar_Diagnostico",
"CURSKIN_A": "Alergia_Pele",
"DXSKIN_A": "Alergia_Pele_Diagnostico",
"PREGNOW_A": "Gravida_Atual",
"HEIGHTTC_A": "Altura",
"WEIGHTLBTC_A": "Peso",
"BMICAT_A": "Categoria_IMC",
"BMICATD_A": "Categoria_IMC_Categoria",
"WEARGLSS_A": "Usa_Oculos",
"VISIONDF_A": "Dificuldade_Visao",
"HEARAID_A": "Usa_Aparelho_Auditivo",
"HEARAIDFR_A": "Frequencia_Uso_Aparelho_Auditivo",
"HEARINGDF_A": "Dificuldade_Audicao",
"HEARQTRM_A": "Dificuldade_Audicao_Sala_Quieta",
"HEARNYRM_A": "Dificuldade_Audicao_Sala_Barulho",
"DIFF_A": "Dificuldade_Andar_ou_Escada",
"EQUIP_A": "Usa_Equipamento_Auxiliar_Mobilidade",
"WLK100_A": "Dificuldade_Caminhar_100yds",
"WLK13M_A": "Dificuldade_Caminhar_1/3_milha",
"STEPS_A": "Dificuldade_Caminhar_12_lances_escada",
"CANEWLKR_A": "Usa_Bengala_ou_Andador",
"WCHAIR_A": "Usa_Cadeira_de_Rodas_ou_Scooter",
"PERASST_A": "Precisa_Ser_Ajudado_Mobilidade",
"NOEQWLK100_A": "Tem_Dificuldade_Caminhar_100yds_sem_equipamento",
"NOEQWLK13M_A": "Tem_Dificuldade_Caminhar_1/3_milha_sem_equipamento",
"NOEQSTEPS_A": "Tem_Dificuldade_Caminhar_12_lances_escada_sem_equipamento",
"EQWLK100_A": "Tem_Dificuldade_Caminhar_100yds_com_equipamento",
"EQWLK13M_A": "Tem_Dificuldade_Caminhar_1/3_milha_com_equipamento",
"EQSTEPS_A": "Tem_Dificuldade_Caminhar_12_lances_escada_com_equipamento",
"COMDIFF_A": "Dificuldade_Comunicar",
"COMUSESL_A": "Usa_Linguagem_Sinais",
"COGMEMDFF_A": "Dificuldade_Memoria_ou_Concentracao",
"COGTYPEDFF_A": "Tipo_Dificuldade_Memoria_ou_Concentracao",
"COGFRQDFF_A": "Frequencia_Dificuldade_Memoria",
"COGAMTDFF_A": "Quantidade_Dificuldade_Memoria",
"UPPSLFCR_A": "Dificuldade_Banhar_ou_vestir_se",
"UPPRAISE_A": "Dificuldade_Levantar_2_litros",
"UPPOBJCT_A": "Dificuldade_Levantar_objeto_pequeno",
"DISAB3_A": "Tem_alguma_deficiencia",
"ANYDIFF_A": "Tem_alguma_deficiencia_funcional",
"SOCERRNDS_A": "Dificuldade_Tarefas_Fora_de_casa",
"SOCSCLPAR_A": "Dificuldade_Atividades_Sociais",
"SOCWRKLIM_A": "Dificuldade_Trabalho_Saude",
"DEVDONSET_A": "Idade_Inicio_Deficiencia_menor_22",
#PLANO SAUDE
"NOTCOV_A": "Sem_cobertura_saude",
"COVER_A": "Tipo_cobertura_saude",
"COVER65_A": "Cobertura_saude_65+",
"SINCOVDE_A": "Cobertura_Dental",
"SINCOVVS_A": "Cobertura_Visao",
"SINCOVRX_A": "Cobertura_Medicamentos",
"MEDICARE_A": "Tem_Medicare",
"MCPART_A": "Tipo_Medicare",
"MCCHOICE_A": "Medicare_Advantage",
"MCHMO_A": "Medicare_HMO",
"MCADVR_A": "Medicare_Advantage_Participacao",
"MCDNCOV_A": "Medicare_Tem_Dental",
"MCVSCOV_A": "Medicare_Tem_Visao",
"MCPARTD_A": "Medicare_Tem_Medicamentos",
"MEDICAID_A": "Medicaid_Info",
"MAXCHNG_A": "Medicaid_Marketplace",
"MAPREM_A": "Medicaid_Premium",
"MADEDUC_A": "Medicaid_Dedutivel",
"MAHDHP_A": "Medicaid_Dedutivel_Anual",
"MAFLG_A": "Privado_para_medicaid",
"PRIVATE_A": "Tem_plano_privado",
"EXCHANGE_A": "Tem_plano_Health_Insurance_Exchange",
"POLHLD1_A": "Dono_plano_saude",
"PRPLCOV1_A": "Plano_saude_outros",
"PRPLCOV1_C_A": "Plano_saude_outros_Crianca",
"PRPOLH1_A": "Parentesco_dono_plano_saude",
"PLNWRKR1_A": "Obtencao_plano_saude",
"PLNEXCHG1_A": "Origem_obtencao_plano_saude",
"PLN1PAY1_A": "Pagador_proprio_plano_saude",
"PLN1PAY2_A": "Pagador_sindicato_chefe_plano_saude",
"PLN1PAY3_A": "Pagador_outro_plano_saude",
"PLN1PAY4_A": "Pagador_medicare_plano_saude",
"PLN1PAY5_A": "Pagador_medicaid_plano_saude",
"PLN1PAY6_A": "Pagador_outro_governo_plano_saude",
"HICOSTR1_A": "Custo_premium_plano_saude",
"PRDEDUC1_A": "Deducao_dono_plano_saude",
"PRHDHP1_A": "Deducao_Alta_dono_plano_saude", #For a plan that covers only one person the deductible threshold is $1,600. For a plan that covers two or more persons the deductible threshold is $3,200
"HSAHRA1_A": "Tem_Health_Savings_Accounts",
"PRRXCOV1_A": "Cobertura_Medicamentos_dono_plano_saude",
"PRDNCOV1_A": "Cobertura_Dental_dono_plano_saude",
"PRVSCOV1_A": "Cobertura_Visao_dono_plano_saude",
"EXCHPR1_A": "Compania_provem_plano_troca",
"PRFLG_A": "Mudou_privado_para_publico",
"PXCHNG1_A": "Mudou_publico_para_privado",
"PRPREM1_A": "Mudou_premium_publico_para_privado",
"PLEXCHPR1_A": "Mudou_publico_para_privado",
"POLHLD2_A": "Dono_plano_saude_2",
"PRPLCOV2_A": "Plano_saude_outros_2",
"PRPOLH2_A": "Parentesco_dono_plano_saude_2",
"PRPLCOV2_C_A": "Plano_saude_outros_2_Crianca",
"PLNWRKR2_A": "Origem_obtencao_plano_saude_2",
"PLNEXCHG2_A": "Origem_obtencao_plano_saude_marketplace_2",
"PLN2PAY1_A": "Pagador_proprio_plano_saude_2",
"PLN2PAY2_A": "Pagador_sindicato_chefe_plano_saude_2",
"PLN2PAY3_A": "Pagador_outro_plano_saude_2",
"PLN2PAY4_A": "Pagador_medicare_plano_saude_2",
"PLN2PAY5_A": "Pagador_medicaid_plano_saude_2",
"PLN2PAY6_A": "Pagador_outro_governo_plano_saude_2",
"HICOSTR2_A": "Custo_premium_plano_saude_2",
"PRDEDUC2_A": "Deducao_dono_plano_saude_2",
"PRHDHP2_A": "Deducao_Alta_dono_plano_saude_2",
"HSAHRA2_A": "Tem_Health_Savings_Accounts_2",
"PRRXCOV2_A": "Cobertura_Medicamentos_dono_plano_saude_2",
"PRDNCOV2_A": "Cobertura_Dental_dono_plano_saude_2",
"PRVSCOV2_A": "Cobertura_Visao_dono_plano_saude_2",
"EXCHPR2_A": "Compania_provem_plano_troca_2",
"CHIP_A": "Tem_Children_Health_Insurance_Program",
"CHXCHNG_A": "CHIP_Marketplace",
"CHPREM_A": "CHIP_Premium",
"CHDEDUC_A": "CHIP_Dedutivel",
"CHHDHP_A": "CHIP_Dedutivel_Anual",
"CHFLG_A": "Mudou_privado_para_CHIP",
"OTHPUB_A": "Tem_plano_publico_estadual",
"OPXCHNG_A": "plano_publico_estadual_marketplace",
"OPPREM_A": "plano_publico_estadual_premium",
"OPDEDUC_A": "plano_publico_estadual_dedutivel",
"OPHDHP_A": "plano_publico_estadual_dedutivel_Anual",
"PLEXCHOP_A": "plano_publico_estadual_tem_plano_de_exchange",
"OPFLG_A": "Mudou_privado_para_plano_publico_estadual",
"OTHGOV_A": "Tem_plano_publico_outro",
"OGXCHNG_A": "plano_publico_outro_marketplace",
"OGPREM_A": "plano_publico_outro_premium",
"OGDEDUC_A": "plano_publico_outro_dedutivel",
"OGHDHP_A": "plano_publico_outro_dedutivel_Anual",
"PLEXCHOG_A": "plano_publico_outro_tem_plano_de_exchange",
"OGFLG_A": "Mudou_privado_para_plano_publico_outro",
"MILITARY_A": "Plano_saude_militar",
"MILSPC1R_A": "Tipo_plano_saude_militar",
"MILSPC2_A": "Tipo_plano_saude_militar", #military related health care
"MILSPC3_A": "Tipo_plano_saude_militar",
"IHS_A": "Usa_plano_saude_indigena",
"HILAST_A": "tempo_ultima_vez_plano_cobriu",
"HILASTMY_A": "quantos_meses_sem_cobertura_12",
"HISTOPJOB_A": "perdeu_cobertura_desemprego",
"HISTOPMISS_A": "perdeu_cobertura_atraso",
"HISTOPAGE_A": "perdeu_cobertura_idade_parou_estudar",
"HISTOPCOST_A":"perdeu_cobertura_preco_aumentou",
"HISTOPELIG_A": "perdeu_cobertura_medicare_medicaid_nao_qualificado",
"RSNHICOST_A": "perdeu_cobertura_muito_caro",
"RSNHIWANT_A": "sem_cobertura_nao_quer",
"RSNHIELIG_A": "sem_cobertura_nao_qualificado",
"RSNHICONF_A": "sem_cobertura_muito_dificil",
"RSNHIMEET_A": "sem_cobertura_nao_acha_plano_necessario",
"RSNHIWAIT_A": "sem_cobertura_esperando",
"RSNHIOTH_A": "sem_cobertura_outro",
"RSNHIJOB_A":"perdeu_cobertura_emprego",
"RSNHIMISS_A": "perdeu_cobertura_atraso",
"HINOTYR_A": "algum_momento_sem_cobertura_12m",
"HINOTMYR_A": "quantos_meses_sem_sobertura",
"MILSPC1_A":"quais_tipo_plano_saude_militar",
"HICOV_A":"tem_plano_saude",
"HIKIND01_A":"mencionou_tipo_privado_plano_saude",
"HIKIND02_A":"mencionou_tipo_medicare_plano_saude",
"HIKIND03_A": "mencionou_tipo_medigap_plano_saude",
"HIKIND04_A": "mencionou_tipo_medicaid_plano_saude",
"HIKIND05_A": "mencionou_tipo_CHIP_plano_saude",
"HIKIND06_A": "mencionou_tipo_militar_plano_saude",
"HIKIND07_A": "mencionou_tipo_indigena_plano_saude",
"HIKIND08_A": "mencionou_tipo_estadual_plano_saude",
"HIKIND09_A": "mencionou_tipo_outro_publico_plano_saude",
"HIKIND10_A": "mencionou_nenhum_plano_saude",
"MCAREPRB_A": "medicare_cobre",
"MCAIDPRB_A": "medicaid_cobre",
#PREOCUPAÇAO SE CONSEGUE PAGAR CUSTOS DE SAUDE
"PAYBLL12M_A":"alguem_teve_problemas_não_conseguiu_pagar_custos_saude_12_meses",
"PAYNOBLLNW_A": "alguem_não_conseguiu_pagar_custos_saude",
"PAYWORRY_A":"se_preocupa_se_consegue_pagar_custos_saude",
#COVID
"EVERCOVD_A": "teve_covid",
"LONGCOVD2_A": "teve_covid_3_meses+",
"SYMPNOW1_A":"tem_sintomas_covid_hoje",
"LCVDACT_A":"impacto_dia_dia_covid_longo",
"CVDSYMSM2_A": "perdeu_olfato_durante_ou_depois_covid",
"CVDPAROS_A":"odores_diferentes_covid",
"CVDSMELCHG_A": "mudanca_odor_covid",
"CVDSMREC2_A": "retornou_odor_covid",
"CVDSYMTST2_A": "perdeu_paladar",
"CVDTSTREC2_A": "recuperou_paladar",
#cuidado preventivo
"LASTDR_A": "ultima_vez_visitou_medico",
"WELLNESS_A": "ultima_visita_bem_estar",
"WELLVIS_A": "tempo_desde_ultima_visita_bem_estar",
"USUALPL_A": "tem_lugar_especifico_para_ir_saude",
"USPLKIND_A": "tipo_lugar_especifico",
"RETAILHC12MTC_A": "quantas_vezes_foi_medico_comum_12_m",
"URGCC12MTC_A": "quantas_vezes_foi_medico_urgente_12_m",
"EMERG12MTC_A": "quantas_vezes_foi_medico_emergencia_12_m",
"HOSPONGT_A": "foi_internado_12_m",
"MEDDL12M_A": "adiou_tratamento_medico_por_custo",
"MEDNG12M_A": "deixou_de_fazer_tratamento_medico_nao_fez_por_custo",
"VIRAPP12M_A": "usou_tratamento_medico_virtual",
"ACCSSINT_A": "tem_acesso_internet",
"ACCSSHOM_A": "tem_acesso_internet_casa",
"HITLOOK_A": "procurou_internet_informacao_saude",
"HITCOMM_A": "usou_internet_para_comunicar_com_medico",
"HITTEST_A": "usou_internet_para_acessar_resultados_exame",
"RX12M_A": "tomou_remedio_12_meses",
#economizou remedio
"RXSK12M_A": "deixou_tomar_remedio_economizar",
"RXLS12M_A": "tomou_menos_remedio_economizar",
"RXDL12M_A": "adiou_cumprir_receita_economizar",
"RXDG12M_A": "precisou_receita_mas_deixou_economizar",
#vacina gravidez
"PREGFLUYR_A": "gravida_epoca_gripe",
"LIVEBIRTH_A": "terminou_gravidez_parto_normal",
"SHTFLU12M_A": "tomou_alguma_vacina_gripe",
"SHTFLUM_A": "mes_ultima_vacina_gripe",
"SHTFLUY_A": "ano_ultima_vacina_gripe",
"FLUPREG_A": "tomou_vacina_antes_durante_gravida",
"FLUPREG2_A": "tomou_vacina__antes_durante_depois_gravida",
#vacina covid
"SHTCVD191_A": "tomou_alguma_vacina_covid",
"SHTCVD19NM2_A": "qtd_vacina_covid",
"CVDVAC1M2_A": "mes_vacina_covid",
"CVDVAC1Y2_A": "ano_vacina_covid",
"SHTPNUEV_A": "tomou_vacina_pneumonia",
"SHTPNEUNB_A": "qtd_vacina_pneumonia",
#herpes zoster
"SHTSHINGL1_A": "tomou_vacina_herpes_zoster",
"SHINGYEARP_A": "ano_vacina_herpes_zoster",
"SHINGWHEN1_A": "vacina_herpes_zoster_antes_2017",
"SHINGRIX3_A": "vacina_herpes_zoster_shingrix",
"SHINGRIXN3_A": "qtd_shingrix",
"SHINGRIXFS1_A": "primeira_ou_segunda_shingrix",
"TDAPPREG_A": "vacinou_coqueluxe_gravidez",
"SHTHEPA_A": "vacinou_hepatite_a",
"WORKHEALTH_A": "trabalha_area_saude",
"WRKHLTHFC_A": "trabalha_em_local_area_saude",
"TRAVEL_A": "viajou_sem_ser_japao_europa_canada_australia_novazelandia",
#ANSIEDADE
"ANXFREQ_A": "frequencia_ansiedade",
"ANXMED_A": "toma_medicacao_ansiedade",
"ANXLEVEL_A": "nivel_ansiedade",
#DEPRESSÃO
"DEPFREQ_A": "frequencia_depressao",
"DEPMED_A": "toma_medicadao_para_depressao",
"DEPLEVEL_A": "nivel_depressao",
#SAUDE MENTAL ACOMPANHAMENTO
"MHRX_A": "tomou_medicacao_concentracao_emocao_comportamento_saude_mental",
"MHTHRPY_A": "acompanhamento_psicoterapico_12_m",
"MHTPYNOW_A": "acompanhando_psicoterapico",
"MHTHDLY_A": "adiou_acompanhamento_psicoterapico_economizar",
"MHTHND_A": "deixou_acompanhamento_psicoterapico_economizar",
#SINTOMAS MENTAIS
"SAD_A": "nada_animou_30_dias",
"NERVOUS_A":"frequencia_nervoso",
"RESTLESS_A": "frequencia_inquieto",
"HOPELESS_A": "frequencia_desesperanca",
"EFFORT_A": "frequencia_tudo_esforço",
"WORTHLESS_A": "frequencia_sentiou_sem_valor",
"K6SPD_A": "passou_dificuldade_psicologica_seria",
#MOVIMENTO REPETITIVO
"REPSTRAIN_A" : "pessoa_teve_doença_movimento_repetitivo",
"REPLIMIT_A": "doença_movimento_repetitivo_serio_suficiente_limitar_por_24h",
"REPSAWDOC_A": "doença_movimento_repetitivo_houve_consulta_medica",
"REPWRKDYTC_A": "doença_movimento_repetitivo_qtd_dias_parado",
"REPFUTWRK_A": "acredita_dias_parado_futuro_doença_movimento_repetitivo",
"REPSTOPCHG_A": "parou_ou_trocou_trabalho_doença_movimento_repetitivo",
"REPREDUCE_A": "modificou_atividades_trabalho_doença_movimento_repetitivo",
"REPWRKCAUS_A": "diagnostico_doença_movimento_repetitivo_pelo_trabalho",
#LESÕES
"ANYINJURY_A": "acidente_ou_lesão_3m",
"INJLIMIT_A": "lesao_limitou_atividades_24h",
"NUMINJTC_A": "qtd_lesoes_3m",
"INJHOME_A": "lesao_ocorreu_casa",
"INJWORK_A": "lesao_ocorreu_trabalho",
"INJSPORTS_A": "lesao_ocorreu_esporte",
"INJFALL_A": "lesao_caiu",
"INJFALLHOM_A": "caiu_casa",
"INJFALLWRK_A": "caiu_trabalho",
#LESAO VEHICULO
"INJMOTOR_A": "lesao_vehiculo",
"INJMVTYPE1_A": "lesao_vehiculo_motorista",
"INJMVTYPE2_A": "lesao_vehiculo_passageiro",
"INJMVTYPE3_A": "lesao_vehiculo_ciclista",
"INJMVTYPE4_A": "lesao_vehiculo_pedestre",
"INJMVTYPE5_A": "lesao_vehiculo_outro",

"INJCHORES_A": "lesao_tarefa_domestica",
"INJSAWDOC_A": "lesao_recebeu_atencao_medico",
"INJER_A": "lesao_recebeu_atencao_sala_emergencia",
"INJHOSP_A": "lesao_internado_hospital",
"INJBONES_A": "lesao_osso_quebrado",
"INJSTITCH_A": "lesao_pontos_grampo",
"INJWRKDYTC_A": "lesao_qtd_dias_perdidos",
"INJFUTWRK_A": "preve_perder_mais_dias",
"INJSTOPCHG_A": "lesao_parou_ou_trocou_emprego",
"INJREDUCE_A": "lesao_modificou_trabalho",
#CONCUSÕES
"TBILCDCMG_A":"lesao_cabeca_perdeu_consciencia_memoria_confuso_12m",
"TBIHLSBMC_A": "lesao_cabeca_sintomas_concusao",
"TBISPORT_A": "lesao_cabeca_esporte",
"TBILEAGUE_A": "lesao_cabeca_esporte_oficial",
"TBIEVAL_A": "lesao_cabeca_diagnostico_concusao_dano_cerebral",
#FATIGA
"FGEFRQTRD_A": "fatiga_frequencia",
"FGELNGTRD_A": "fatiga_duracao",
"FGELEVTRD_A": "fatiga_nivel",
#CIGARRO
"SMKEV_A": "fumou_100_cigarros",
"SMKAGE_A": "fumante_idade_comecou",
"SMKNOW_A": "fumante_fuma",
"SMKCIGST_A": "fumante_status",
"CIGNOW_A": "fumante_qtd_cigagrros",
"SMK30D_A": "fumante_dias_ultimo_mes",
"CIG30D_A": "fumante_qtd_ultimo_mes",
"MENTHOLC_A": "fumante_mentol",
"SMKQT12M_A": "fumante_tentou_parar_12m",
"SMKQTTP_A": "fumante_tempo_sem_fumar",
"SMKQTNP_A": "fumante_tempo_sem_fumar_dias",
"SMKQTY_A": "fumante_tempo_sem_fumar_anos",
"MENTHOLF_A": "fumante_parou_fumava_mentol",
"AVGNUMCIG_A": "fumante_media_cigarros",
"AVGPACKCIG_A": "fumante_media_pacotes",
"SMKTLK1_A": "fumante_recebeu_recomendacao_parar",
"ECIGEV_A": "fumante_usou_cigarro_eletrico",
"ECIGNOW_A": "fumante_usa_cigarro_eletrico",
"SMKECIGST_A": "fumante_cigarro_eletrico_status",
"CIGAREV_A": "fumante_pelo_menos_um_charuto",
"CIGARCUR_A": "fumante_fuma_charuto",
"CIGAR30D_A": "fumante_charuto_30d",
"SMOKELSEV1_A": "ja_usou_tabaco_sem_fumaca",
"SMOKELSCR1_A": "usa_tabaco_sem_fumaca",
"CTSCANEV1_A": "tomografia_peito",
"CTLNGWHN1_A": "tomografia_peito_mais_recente",
"CTLNGCAN1_A": "tomografia_peito_motivo_cancer",
#ALCOOL
"DRKLIFE_A": "bebeu_alcool_vida",
"DRK12MN_A": "bebeu_alcool_qtd_dias_ultimo_ano_resp",
"DRK12MTP_A": "bebeu_alcool_frequencia_dias_ultimo_ano_resp",
"DRK12MWK_A": "bebeu_alcool_frequencia_por_semana_ultimo_ano",
"DRK12MYR_A": "bebeu_alcool_qtd_dias_ultimo_ano",
"DRKAVG12M_A": "bebeu_alcool_media_drinks",
"DRK12ANYR_A": "bebeu_alcool_ultimo_ano",
"DRKSTAT_A": "bebeu_alcool_status",
"DRKBNG12M_A": "bebeu_alcool_binge",
"DRKANY30D_A": "bebeu_alcool_ultimo_mes",
"DRKBNG30D_A": "bebeu_alcool_binge_vezes_ultimo_mes",
"DRKHVY12M_A": "bebeu_alcool_uso_pesado",
"DRKADVISE1_A": "bebeu_alcool_recomendado_parar",
#ATIVIDADE FISICA
"MODNR_A": "atividade_fisica_moderada_qtd_resp",
"MODTPR_A": "atividade_fisica_moderada_freq_resp",
"MODFREQW_A": "atividade_fisica_moderada_freq_por_semana",
"MODLNR_A": "atividade_fisica_moderada_qtd_tempo_resp",
"MODLTPR_A": "atividade_fisica_moderada_medida_tempo_resp",
"MODMIN_A": "atividade_fisica_moderada_minutos_duracao",
"VIGNR_A": "atividade_fisica_pesada_qtd_resp",
"VIGTPR_A": "atividade_fisica_pesada_freq_resp",
"VIGFREQW_A": "atividade_fisica_pesada_freq_por_semana",
"VIGLNR_A": "atividade_fisica_pesada_qtd_tempo_resp",
"VIGLTPR_A": "atividade_fisica_pesada_medida_tempo_resp",
"VIGMIN_A": "atividade_fisica_pesada_minutos_duracao",
"PA18_02R_A": "atividade_fisica_atingiu_meta_aerobica",

"STRNR_A": "atividade_fisica_aumentar_forca_qtd_resp",
"STRTPR_A": "atividade_fisica_aumentar_forca_freq_resp",
"STRFREQW_A": "atividade_fisica_aumentar_forca_vzs_semana",
"PA18_05R_A": "atividade_fisica_atingiu_meta_aerobica_meta_forca_ambos",

"WLKTRAN_A": "andou_forma_transporte",
"WLKTRANDAY_A": "andou_forma_transporte_dias_resp",
"WLKTRANTPD_A": "andou_forma_transporte_vezes_resp",
"WLKTRANTC_A": "andou_forma_transporte_minutos",
"WLKLEIS_A": "caminhou_prazer",
"WLKLEISDAY_A": "caminhou_prazer_dias",
"WLKLEISTPD_A": "caminhou_prazer_vezes_dia",
"WLKLEISTC_A": "caminhou_prazer_minutos",
"HOMEWLK_A": "caminhou_perto_casa",
"ROADSWLK_A": "bairro_caminhavel",
"SHOPSWLK_A": "bairro_caminhavel_lojas",
"TRANSITWLK_A": "bairro_caminhavel_ponto_transporte",
"FUNWLK_A": "bairro_caminhavel_divertido",
"RELAXWLK_A" : "bairro_caminhavel_relaxante",
"SIDEWLK_A" : "bairro_caminhavel_calcada",
"TRAFFICWLK_A": "bairro_caminhavel_transito_inseguro",
"CRIMEWLK_A": "bairro_caminhavel_crime_inseguro",
"ANIMALWLK_A": "bairro_caminhavel_animais_inseguro",
"WEATHERWLK_A": "frequencia_clima_afeta_caminhada",
"PEOPLEWLK_A": "frequencia_pessoas_caminham_frente_casa",
"ADVACTIVE_A": "atividade_fisica_recomendado",

#ESPOSIÇÃO SOLAR
"SUNSKIN1_A": "reacao_sol",
"SUNTAN1_A": "freq_bronzear",
"ANYSBURN1_A": "teve_queimadura_solar",
"NUMBRN1TC_A": "qtd_queimadura_solar",
"SBURNWRK_A": "motivo_queimadura_solar_trabalho",
"SBURNTAN_A": "motivo_queimadura_solar_bronzear",
"SBURNPHY_A": "motivo_queimadura_solar_exercicio",
"SBURNWAT_A": "queimadura_solar_prox_agua",
"SBURNSCR_A": "queimadura_solar_usou_protetor",
"SBURNALC_A": "queimadura_solar_bebeu_alcool",

#REMEDIOS DE SONO
"SLPMEDINTRO_A": "recebeu_intro_remedios_sono",
"SLPHOURS_A": "qtd_horas_sono_dia",
"SLPREST_A": "freq_sono_acordou_descansado",
"SLPFLL_A": "dificuldade_comecar_dormir_30d",
"SLPSTY_A": "dificuldade_continuar_dormir_30d",
"SLPMED1_A": "freq_tomou_remedio_controlado_dormir",
"SLPMED2_A": "freq_tomou_remedio_venda_livre_dormir",
"SLPMED3_A": "freq_tomou_remedio_maconha_dormir",

#SOLIDAO
"SUPPORT_A": "suporte_social_emocional_frequencia",
"LONELY_A": "solidão_frequencia",

#paladar e olfato
"SMELLDF_A": "teve_dificuldade_olfato",
"SMELLCOMP_A": "melhora_piora_olfato_com_tempo",
"SMELLPHT_A": "olfato_hallucinou_cheiro_metalico_queimado",
"SMELLPAR_A": "olfato_cheiros_mudaram",
"TASTEDF_A": "teve_dificuldade_paladar",
"TASTECOMP_A": "melhora_piora_paladar_com_tempo",
"TASTEFLAV_A": "melhora_piora_paladar_com_tempo_exemplo",
"TASTEUNW_A": "paladar_distorcao_gosto",
"TSTSMHP2_A": "conversou_medico_sobre_paladar_olfato",
"TSTSMLAST_A": "quando_conversou_medico_sobre_paladar_olfato",

#Vida pessoal
"ORIENT_A": "orientação_sexual",
"MARITAL_A": "estado_civil",
"SPOUSLIV_A": "conjuge_mora_aqui",
"SPOUSEP_A": "conjuge_nao_mora_aqui_motivo",
"EVRMARRIED_A": "ja_foi_casado",
"MARSTAT_A": "conjuge_presente",
"LEGMSTAT_A": "estado_civil_status",
"SPOUSESEX_A": "sexo_conjuge",
"SASPPRACE_A": "casal_mesma_raca",
"SASPPHISP_A": "casal_mesma_etinia_hispanica",
"SPOUSAGETC_A": "conjuge_idade",
"SPOUSEDUCP_A": "conjuge_nivel_escolaridade",
"SPOUSWRK_A": "conjuge_trabalha",
"SPOUSWKFT_A": "conjuge_trabalha_full_time",
"PRTNRSEX_A": "companheiro_sexo",
"PRTNRAGETC_A": "companheiro_idade",
"PRTNREDUCP_A": "companheiro_nivel_escolaridade",
"PRTNRWRK_A": "companheiro_trabalha",
"PRTNRWKFT_A": "companheiro_trabalha_full_time",
"SAPARENTSC_A": "adulto_parentesco_crianca",
"PARSTAT_A": "adulto_parentesco_crianca",

#VETERANO

"AFVET_A": "militar_ja_foi",
"AFVETTRN_A": "reserva_guarda_nacional",
"COMBAT_A": "combateu",
"VADISB_A": "tem_deficiencia_veterano_adm",
"VAHOSP_A": "usou_tratamento_veterano_adm_12m",
"VACAREEV_A": "usou_tratamento_veterano_adm",

#naturalidade

"NATUSBORN_A" : "nasceu_EUA",
"YRSINUS_A": "tempo_nos_EUA",
"CITZNSTP_A": "cidadania_status",
"LANGHM_A": "fala_outra_lingua_casa",
"LANGSPECR_A": "lingua_falada",
"LANGDOC_A": "lingua_falada_medico",
"LANGMED_A": "lingua_consumo_midia",
"LANGSOC_A": "lingua_falada_social",

#TRABALHO e RENDA
"SCHCURENR_A": "estuda",
"SCHDYMSSTC_A": "estuda_dias_perdidos_saude",
"EMPLASTWK_A": "trabalhou_semana_passada",
"EMPNOWRK_A": "temporariamente_nao_trabalhou_semana_passada",
"EMPWHYNOT_A": "nao_trabalhou_semana_passada_motivo",
"EMPWHENWRK_A": "nao_trabalhou_quanto_tempo",
"EMPWRKLSW1_A": "trabalhou_semana_passada",
"EMPLSTWOR1_A": "ultima_vez_trabalhou",
"EMPLSTWOR1_A": "horas_trabalhadas_por_semana",
"EMPWRKFT1_A": "normalmente_trabalha_35h_semana",
"EMPSICKLV_A": "trabalho_tem_sickleave",
"EMPHEALINS_A": "trabalho_oferece_plano_saude",
"EMPDYSMSS3_A": "trabalho_dias_doente",
"EMDINDSTN1_A": "trabalho_industria",
"EMDINDSTN2_A": "trabalho_industria_recode",
"EMDOCCUPN1_A": "trabalho_cargo",
"EMDOCCUPN2_A": "trabalho_area_cargo",
"EMDSUPER_A": "trabalho_supervisor",
"EMDWRKCAT1_A": "empregador",
"CEVOLUN1_A": "trabalhou_voluntariado_organizacao",
"CEVOLUN2_A": "trabalhou_voluntariado_outros",
"PCNTADWKP1_A": "adultos_trabalhando_casa",
"PCNTADWFP1_A": "adultos_trabalhando_casa_fulltime",
"INCWRKO_A": "recebeu_renda_trabalhando",
"INCINTER_A": "recebeu_renda_investimento",
"INCSSRR_A": "recebeu_renda_seguranca_social",
"INCSSISSDI_A": "recebeu_renda_SSI_ou_SSDI",
"SSISSDIBTH_A": "qual_renda_assistencial",
"SSISSDIDSB_A": "SSI/SSDI due to disability",
"INCWELF_A": "recebeu_renda_assistencial",
"INCRETIRE_A": "recebeu_renda_aposentadoria",
"INCOTHR_A": "recebeu_renda_outros",
"IMPNUM_A": "inputation number",
"POVRATTC_A": "nivel_pobreza",
"RATCAT_A": "razao_renda_por_limiar_pobreza",
"IMPINCFLG_A": "Imputed SA family income imputation flag",
"INCTCFLG_A": "Sample adult family income top-code flag",

#ALIMENTAÇÃO
"FSNAP12M_A": "recebeu_vale_refeicao_12m",
"FSNAP30D_A": "recebeu_vale_refeicao_30d",
"FWIC12M_A": "recebeu_beneficio_programa_mulheres_criancas",
"FLUNCH12M1_A": "recebeu_gratuidade_desconto_alimentos_escola",
"FDSRUNOUT_A": "preocupacao_comida_acabar",
"FDSLAST_A": "comida_nao_suficiente",
"FDSBALANCE_A": "sem_dinheiro_comer_forma_balanceada",
"FDSSKIP_A": "comeu_menos_pulou_refeicao_sem_dinheiro",
"FDSSKIPDYS_A": "quantos_dias_comeu_menos_pulou_refeicao_sem_dinheiro",
"FDSLESS_A": "comeu_menos_que_deveria",
"FDSHUNGRY_A": "passou_fome_nao_comeu_sem_dinheiro",
"FDSWEIGHT_A": "nao_comeu_perdeu_peso",
"FDSNOTEAT_A": "nao_comeu_um_dia_inteiro",
"FDSNEDAYS_A": "quantos_dia_nao_comeu",
"FDSCAT3_A": "nivel_seguranca_alimentar",
"FDSCAT4_A": "nivel_seguranca_alimentar2",


"HOUYRSLIV_A": "tempo_morando_neste_imovel",
"HOUTENURE_A": "dono_imovel",
"HOUGVASST_A": "pagando_menos_aluguel",
"HOUSECOST_A": "dificuldade_pagando_moradia",

"TRANSPOR_A": "nao_foi_medico_sem_transporte_12m",
"CEMMETNG_A": "foi_reuniao_publica",
"CEVOTELC_A": "votou_ultima_eleicao",


})

df_adult24

,razao_renda_por_limiar_pobreza,Sample adult family income top-code flag,Imputed SA family income imputation flag,Pseudo_Primary_Sampling_Unit,Pseudo_Stratum,caminhou_prazer_minutos,andou_forma_transporte_minutos,Composicao_Hispanica_Raca_Etnia,Raca_Etnia,Tem_alguma_deficiencia_funcional,Tem_alguma_deficiencia,qtd_queimadura_solar,passou_dificuldade_psicologica_seria,estuda_dias_perdidos_saude,Trabalha_militar,doença_movimento_repetitivo_qtd_dias_parado,tempo_nos_EUA,cidadania_status,companheiro_nivel_escolaridade,conjuge_nivel_escolaridade,estado_civil_status,conjuge_presente,casal_mesma_raca,casal_mesma_etinia_hispanica,companheiro_idade,conjuge_idade,companheiro_trabalha_full_time,companheiro_trabalha,conjuge_trabalha_full_time,conjuge_trabalha,sexo_conjuge,companheiro_sexo,lesao_qtd_dias_perdidos,qtd_lesoes_3m,ano_vacina_herpes_zoster,Parentesco_Responde_Proxy,Flag_Responde_Proxy,Flag_Respondente_Domicilio,adultos_trabalhando_casa_fulltime,adultos_trabalhando_casa,nivel_seguranca_alimentar2,nivel_seguranca_alimentar,trabalho_dias_doente,horas_trabalhadas_por_semana,normalmente_trabalha_35h_semana,trabalhou_semana_passada,EMPWKHRS3_A,trabalho_area_cargo,trabalho_cargo,trabalho_industria_recode,trabalho_industria,DIBAGETC_A,Idade_diagnostico_diabetes,fumante_tempo_sem_fumar_dias,fumante_tempo_sem_fumar_anos,fumante_cigarro_eletrico_status,fumante_status,Categoria_IMC_Categoria,Categoria_IMC,Peso,Altura,bebeu_alcool_uso_pesado,bebeu_alcool_status,bebeu_alcool_qtd_dias_ultimo_ano,bebeu_alcool_frequencia_por_semana_ultimo_ano,quantas_vezes_foi_medico_comum_12_m,quantas_vezes_foi_medico_urgente_12_m,quantas_vezes_foi_medico_emergencia_12_m,mudanca_odor_covid,atividade_fisica_atingiu_meta_aerobica_meta_forca_ambos,atividade_fisica_atingiu_meta_aerobica,atividade_fisica_moderada_freq_por_semana,atividade_fisica_moderada_qtd_resp,atividade_fisica_moderada_freq_resp,atividade_fisica_moderada_qtd_tempo_resp,atividade_fisica_moderada_medida_tempo_resp,atividade_fisica_moderada_minutos_duracao,atividade_fisica_pesada_qtd_resp,atividade_fisica_pesada_freq_resp,atividade_fisica_pesada_qtd_tempo_resp,atividade_fisica_pesada_medida_tempo_resp,atividade_fisica_pesada_freq_por_semana,atividade_fisica_pesada_minutos_duracao,atividade_fisica_aumentar_forca_freq_resp,atividade_fisica_aumentar_forca_qtd_resp,atividade_fisica_aumentar_forca_vzs_semana,Quantos_maiores_18_casa,Quantos_menores_18_casa,lingua_falada,Cobertura_saude_65+,Tipo_cobertura_saude,Tem_plano_Health_Insurance_Exchange,Sem_cobertura_saude,Tipo_plano_saude_militar,Mudou_privado_para_plano_publico_outro,Mudou_privado_para_plano_publico_estadual,Mudou_privado_para_CHIP,Privado_para_medicaid,Origem_obtencao_plano_saude_2,Obtencao_plano_saude,perdeu_cobertura_atraso,perdeu_cobertura_emprego,Medicare_Advantage_Participacao,Mudou_privado_para_publico,Mudou_publico_para_privado,Mudou_premium_publico_para_privado,Mudou_publico_para_privado,Custo_premium_plano_saude_2,Custo_premium_plano_saude,Tem_plano_publico_outro,Tem_plano_publico_estadual,Usa_plano_saude_indigena,Plano_saude_militar,Tem_Children_Health_Insurance_Program,Medicaid_Info,Tem_Medicare,Tem_plano_privado,Plano_saude_outros_Crianca,Plano_saude_outros_2_Crianca,plano_publico_outro_tem_plano_de_exchange,plano_publico_estadual_tem_plano_de_exchange,Compania_provem_plano_troca_2,Compania_provem_plano_troca,Educacao,Educacao_Maxima_casa,adulto_parentesco_crianca,adulto_parentesco_crianca,Flag_Multifamiliar,Flag_Adulto_65+_casa,Quantos_adultos_casa,Quantos_criancas_casa,Numero_total_cancer,Idade_diagnostico_cancer_colorretal,Idade_diagnostico_cancer_cabeca_pescoco,Idade_diagnostico_outro_cancer,Idade_diagnostico_cancer_utero,Idade_diagnostico_cancer_tireoide,Idade_diagnostico_cancer_faringe,Idade_diagnostico_cancer_estomago,Idade_diagnostico_cancer_pele_desconhecido,Idade_diagnostico_cancer_pele_nao_melanoma,Idade_diagnostico_cancer_pele_melanoma,Idade_diagnostico_cancer_reto,Idade_diagnostico_cancer_prostata,Idade_diagnostico_cancer_pancreas,Idade_diagnostico_cancer_ovario,Idade_diagnostico_cancer_boca,Idade_diagnostico_cancer_melanoma,Idade_diagnostico_cancer_linfoma,Idade_diagnostico_cancer_pulmao,Idade_diagnostico_cancer_figado,Idade_diagnostico_cancer_leucemia,Idade_diagnostico_cancer_laringe,Idade_diagnostico_cancer_vesicula_biliar,Idade_diagnostico_cancer_esofago,Idade_diagnostico_cancer_colon,Idade_diagnostico_cancer_cervix,Idade_diagnostico_cancer_mama,Idade_diagnostico_cancer_cerebro,Idade_diagnostico_cancer_osso,Idade_diagnostico_cancer_sangue,Idade_diagnostico_cancer_bexiga,Teve_outro_cancer,Teve_cancer_colorretal,Teve_cancer_cabeca_pescoco,Teve_cancer_utero,Teve_cancer_tireoide,Teve_cancer_faringe,Teve_cancer_estomago,Teve_cancer_pele_desconhecido,Teve_cancer_pele_nao_melanoma,Teve_cancer_pele_melanoma,Teve_cancer_reto,Teve_cancer_prostata,Teve_cancer_pancreas,Teve_cancer_ovario,Teve_cancer_boca,Teve_cancer_melanoma,Teve_cancer_linfoma,Teve_cancer_pulmao,Teve_cancer_figado,Teve_cancer_leucemia,Teve_cancer_laringe,Teve_cancer_vesicula_biliar,Teve_cancer_esofago,Teve_cancer_colon,Teve_cancer_cervix,Teve_cancer_mama,Teve_cancer_cerebro,Teve_cancer_osso,Teve_cancer_sangue,Teve_cancer_bexiga,Mexico_Origem_Hispanica,Origem_Hispanica,Area_Urbana,Região,Trimestre_Entrevista,Ano_Pesquisa,Sexo,Idade,Quantos_adultos_com_65+_casa,Entrevista_Completude,votou_ultima_eleicao,foi_reuniao_publica,nao_foi_medico_sem_transporte_12m,dificuldade_pagando_moradia,pagando_menos_aluguel,dono_imovel,tempo_morando_neste_imovel,quantos_dia_nao_comeu,nao_comeu_um_dia_inteiro,nao_comeu_perdeu_peso,passou_fome_nao_comeu_sem_dinheiro,comeu_menos_que_deveria,quantos_dias_comeu_menos_pulou_refeicao_sem_dinheiro,comeu_menos_pulou_refeicao_sem_dinheiro,sem_dinheiro_comer_forma_balanceada,comida_nao_suficiente,preocupacao_comida_acabar,recebeu_gratuidade_desconto_alimentos_escola,recebeu_beneficio_programa_mulheres_criancas,recebeu_vale_refeicao_30d,recebeu_vale_refeicao_12m,recebeu_renda_outros,recebeu_renda_aposentadoria,recebeu_renda_assistencial,SSI/SSDI due to disability,qual_renda_assistencial,recebeu_renda_SSI_ou_SSDI,recebeu_renda_seguranca_social,recebeu_renda_investimento,recebeu_renda_trabalhando,trabalhou_voluntariado_outros,trabalhou_voluntariado_organizacao,empregador,trabalho_supervisor,trabalho_oferece_plano_saude,trabalho_tem_sickleave,nao_trabalhou_quanto_tempo,nao_trabalhou_semana_passada_motivo,temporariamente_nao_trabalhou_semana_passada,trabalhou_semana_passada,estuda,lingua_falada_social,lingua_falada_medico,lingua_consumo_midia,fala_outra_lingua_casa,nasceu_EUA,usou_tratamento_veterano_adm,usou_tratamento_veterano_adm_12m,tem_deficiencia_veterano_adm,combateu,reserva_guarda_nacional,militar_ja_foi,ja_foi_casado,conjuge_nao_mora_aqui_motivo,conjuge_mora_aqui,estado_civil,orientação_sexual,quando_conversou_medico_sobre_paladar_olfato,conversou_medico_sobre_paladar_olfato,paladar_distorcao_gosto,melhora_piora_paladar_com_tempo_exemplo,melhora_piora_paladar_com_tempo,teve_dificuldade_paladar,olfato_cheiros_mudaram,olfato_hallucinou_cheiro_metalico_queimado,melhora_piora_olfato_com_tempo,teve_dificuldade_olfato,solidão_frequencia,suporte_social_emocional_frequencia,freq_tomou_remedio_maconha_dormir,freq_tomou_remedio_venda_livre_dormir,freq_tomou_remedio_controlado_dormir,recebeu_intro_remedios_sono,dificuldade_continuar_dormir_30d,dificuldade_comecar_dormir_30d,freq_sono_acordou_descansado,qtd_horas_sono_dia,queimadura_solar_bebeu_alcool,queimadura_solar_usou_protetor,queimadura_solar_prox_agua,motivo_queimadura_solar_exercicio,motivo_queimadura_solar_bronzear,motivo_queimadura_solar_trabalho,teve_queimadura_solar,freq_bronzear,reacao_sol,atividade_fisica_recomendado,frequencia_pessoas_caminham_frente_casa,frequencia_clima_afeta_caminhada,bairro_caminhavel_animais_inseguro,bairro_caminhavel_crime_inseguro,bairro_caminhavel_transito_inseguro,bairro_caminhavel_calcada,bairro_caminhavel_relaxante,bairro_caminhavel_divertido,bairro_caminhavel_ponto_transporte,bairro_caminhavel_lojas,bairro_caminhavel,caminhou_perto_casa,caminhou_prazer_vezes_dia,caminhou_prazer_dias,caminhou_prazer,andou_forma_transporte_vezes_resp,andou_forma_transporte_dias_resp,andou_forma_transporte,bebeu_alcool_recomendado_parar,bebeu_alcool_binge_vezes_ultimo_mes,bebeu_alcool_ultimo_mes,bebeu_alcool_binge,bebeu_alcool_ultimo_ano,bebeu_alcool_media_drinks,bebeu_alcool_frequencia_dias_ultimo_ano_resp,bebeu_alcool_qtd_dias_ultimo_ano_resp,bebeu_alcool_vida,tomografia_peito_motivo_cancer,tomografia_peito_mais_recente,tomografia_peito,usa_tabaco_sem_fumaca,ja_usou_tabaco_sem_fumaca,fumante_charuto_30d,fumante_fuma_charuto,fumante_pelo_menos_um_charuto,fumante_usa_cigarro_eletrico,fumante_usou_cigarro_eletrico,fumante_recebeu_recomendacao_parar,fumante_media_pacotes,fumante_parou_fumava_mentol,fumante_tempo_sem_fumar,fumante_tentou_parar_12m,fumante_mentol,fumante_qtd_ultimo_mes,fumante_dias_ultimo_mes,fumante_qtd_cigagrros,fumante_fuma,fumante_idade_comecou,fumou_100_cigarros,fatiga_nivel,fatiga_duracao,fatiga_frequencia,lesao_cabeca_diagnostico_concusao_dano_cerebral,lesao_cabeca_esporte_oficial,lesao_cabeca_esporte,lesao_cabeca_sintomas_concusao,lesao_cabeca_perdeu_consciencia_memoria_confuso_12m,lesao_modificou_trabalho,lesao_parou_ou_trocou_emprego,preve_perder_mais_dias,lesao_pontos_grampo,lesao_osso_quebrado,lesao_internado_hospital,lesao_recebeu_atencao_sala_emergencia,lesao_recebeu_atencao_medico,lesao_tarefa_domestica,lesao_vehiculo_outro,lesao_vehiculo_pedestre,lesao_vehiculo_ciclista,lesao_vehiculo_passageiro,lesao_vehiculo_motorista,lesao_vehiculo,caiu_trabalho,caiu_casa,lesao_caiu,lesao_ocorreu_esporte,lesao_ocorreu_trabalho,lesao_ocorreu_casa,lesao_limitou_atividades_24h,acidente_ou_lesão_3m,diagnostico_doença_movimento_repetitivo_pelo_trabalho,modificou_atividades_trabalho_doença_movimento_repetitivo,parou_ou_trocou_trabalho_doença_movimento_repetitivo,acredita_dias_parado_futuro_doença_movimento_repetitivo,doença_movimento_repetitivo_houve_consulta_medica,doença_movimento_repetitivo_serio_suficiente_limitar_por_24h,pessoa_teve_doença_movimento_repetitivo,frequencia_sentiou_sem_valor,frequencia_tudo_esforço,frequencia_desesperanca,frequencia_inquieto,frequencia_nervoso,nada_animou_30_dias,deixou_acompanhamento_psicoterapico_economizar,adiou_acompanhamento_psicoterapico_economizar,acompanhando_psicoterapico,acompanhamento_psicoterapico_12_m,tomou_medicacao_concentracao_emocao_comportamento_saude_mental,nivel_depressao,toma_medicadao_para_depressao,frequencia_depressao,nivel_ansiedade,toma_medicacao_ansiedade,frequencia_ansiedade,viajou_sem_ser_japao_europa_canada_australia_novazelandia,trabalha_em_local_area_saude,trabalha_area_saude,vacinou_hepatite_a,vacinou_coqueluxe_gravidez,primeira_ou_segunda_shingrix,qtd_shingrix,vacina_herpes_zoster_shingrix,vacina_herpes_zoster_antes_2017,tomou_vacina_herpes_zoster,qtd_vacina_pneumonia,tomou_vacina_pneumonia,ano_vacina_covid,mes_vacina_covid,qtd_vacina_covid,tomou_alguma_vacina_covid,tomou_vacina__antes_durante_depois_gravida,tomou_vacina_antes_durante_gravida,ano_ultima_vacina_gripe,mes_ultima_vacina_gripe,tomou_alguma_vacina_gripe,terminou_gravidez_parto_normal,gravida_epoca_gripe,precisou_receita_mas_deixou_economizar,adiou_cumprir_receita_economizar,tomou_menos_remedio_economizar,deixou_tomar_remedio_economizar,tomou_remedio_12_meses,usou_internet_para_acessar_resultados_exame,usou_internet_para_comunicar_com_medico,procurou_internet_informacao_saude,tem_acesso_internet_casa,tem_acesso_internet,usou_tratamento_medico_virtual,deixou_de_fazer_tratamento_medico_nao_fez_por_custo,adiou_tratamento_medico_por_custo,foi_internado_12_m,tipo_lugar_especifico,tem_lugar_especifico_para_ir_saude,tempo_desde_ultima_visita_bem_estar,ultima_visita_bem_estar,ultima_vez_visitou_medico,recuperou_paladar,perdeu_paladar,retornou_odor_covid,odores_diferentes_covid,perdeu_olfato_durante_ou_depois_covid,impacto_dia_dia_covid_longo,tem_sintomas_covid_hoje,teve_covid_3_meses+,teve_covid,se_preocupa_se_consegue_pagar_custos_saude,alguem_não_conseguiu_pagar_custos_saude,alguem_teve_problemas_não_conseguiu_pagar_custos_saude_12_meses,quantos_meses_sem_sobertura,algum_momento_sem_cobertura_12m,sem_cobertura_outro,sem_cobertura_esperando,sem_cobertura_nao_acha_plano_necessario,sem_cobertura_muito_dificil,sem_cobertura_nao_qualificado,sem_cobertura_nao_quer,perdeu_cobertura_muito_caro,perdeu_cobertura_medicare_medicaid_nao_qualificado,perdeu_cobertura_preco_aumentou,perdeu_cobertura_idade_parou_estudar,perdeu_cobertura_atraso,perdeu_cobertura_desemprego,quantos_meses_sem_cobertura_12,tempo_ultima_vez_plano_cobriu,Tipo_plano_saude_militar,Tipo_plano_saude_militar,quais_tipo_plano_saude_militar,plano_publico_outro_dedutivel_Anual,plano_publico_outro_dedutivel,plano_publico_outro_premium,plano_publico_outro_marketplace,plano_publico_estadual_dedutivel_Anual,plano_publico_estadual_dedutivel,plano_publico_estadual_premium,plano_publico_estadual_marketplace,CHIP_Dedutivel_Anual,CHIP_Dedutivel,CHIP_Premium,CHIP_Marketplace,Cobertura_Visao_dono_plano_saude_2,Cobertura_Visao_dono_plano_saude,Cobertura_Dental_dono_plano_saude_2,Cobertura_Dental_dono_plano_saude,Cobertura_Medicamentos_dono_plano_saude_2,Cobertura_Medicamentos_dono_plano_saude,Tem_Health_Savings_Accounts_2,Tem_Health_Savings_Accounts,Deducao_Alta_dono_plano_saude_2,Deducao_Alta_dono_plano_saude,Deducao_dono_plano_saude_2,Deducao_dono_plano_saude,Pagador_outro_governo_plano_saude_2,Pagador_medicaid_plano_saude_2,Pagador_medicare_plano_saude_2,Pagador_outro_plano_saude_2,Pagador_sindicato_chefe_plano_saude_2,Pagador_proprio_plano_saude_2,Pagador_outro_governo_plano_saude,Pagador_medicaid_plano_saude,Pagador_medicare_plano_saude,Pagador_outro_plano_saude,Pagador_sindicato_chefe_plano_saude,Pagador_proprio_plano_saude,Origem_obtencao_plano_saude_marketplace_2,Origem_obtencao_plano_saude,Parentesco_dono_plano_saude_2,Parentesco_dono_plano_saude,Plano_saude_outros_2,Plano_saude_outros,Dono_plano_saude_2,Dono_plano_saude,Medicaid_Dedutivel_Anual,Medicaid_Dedutivel,Medicaid_Premium,Medicaid_Marketplace,Medicare_Tem_Medicamentos,Medicare_Tem_Visao,Medicare_Tem_Dental,Medicare_HMO,Medicare_Advantage,Tipo_Medicare,Cobertura_Medicamentos,Cobertura_Visao,Cobertura_Dental,medicaid_cobre,medicare_cobre,mencionou_nenhum_plano_saude,mencionou_tipo_outro_publico_plano_saude,mencionou_tipo_estadual_plano_saude,mencionou_tipo_indigena_plano_saude,mencionou_tipo_militar_plano_saude,mencionou_tipo_CHIP_plano_saude,mencionou_tipo_medicaid_plano_saude,mencionou_tipo_medigap_plano_saude,mencionou_tipo_medicare_plano_saude,mencionou_tipo_privado_plano_saude,tem_plano_saude,Idade_Inicio_Deficiencia_menor_22,Dificuldade_Trabalho_Saude,Dificuldade_Atividades_Sociais,Dificuldade_Tarefas_Fora_de_casa,Dificuldade_Levantar_objeto_pequeno,Dificuldade_Levantar_2_litros,Dificuldade_Banhar_ou_vestir_se,Quantidade_Dificuldade_Memoria,Frequencia_Dificuldade_Memoria,Tipo_Dificuldade_Memoria_ou_Concentracao,Dificuldade_Memoria_ou_Concentracao,Usa_Linguagem_Sinais,Dificuldade_Comunicar,Tem_Dificuldade_Caminhar_12_lances_escada_com_equipamento,Tem_Dificuldade_Caminhar_1/3_milha_com_equipamento,Tem_Dificuldade_Caminhar_100yds_com_equipamento,Tem_Dificuldade_Caminhar_12_lances_escada_sem_equipamento,Tem_Dificuldade_Caminhar_1/3_milha_sem_equipamento,Tem_Dificuldade_Caminhar_100yds_sem_equipamento,Precisa_Ser_Ajudado_Mobilidade,Usa_Cadeira_de_Rodas_ou_Scooter,Usa_Bengala_ou_Andador,Dificuldade_Caminhar_12_lances_escada,Dificuldade_Caminhar_1/3_milha,Dificuldade_Caminhar_100yds,Usa_Equipamento_Auxiliar_Mobilidade,Dificuldade_Andar_ou_Escada,Dificuldade_Audicao_Sala_Barulho,Dificuldade_Audicao_Sala_Quieta,Dificuldade_Audicao,Frequencia_Uso_Aparelho_Auditivo,Usa_Aparelho_Auditivo,Dificuldade_Visao,Usa_Oculos,Gravida_Atual,Alergia_Pele_Diagnostico,Alergia_Pele,Alergia_Alimentar_Diagnostico,Alergia_Alimentar,Alergia_Respiratoria_Diagnostico,Alergia_Respiratoria,Condicao_Imunocomprometida,Tratamento_Imunosupressor,Boca_Seca_12_meses,Resfriado_Gripe_12_meses_mais_1_mes,Fatiga_Cronica_Hoje,Fatiga_Cronica_Diagnostico,Psoriase_Diagnostico,Colite_Ulcerativa_Diagnostico,Doenca_Crohn_Diagnostico,Doenca_Figado_Diagnostico,Hepatite_Diagnostico,Doenca_Rim_Diagnostico,Depressao_Diagnostico,Ansiedade_Diagnostico,Demencia_Diagnostico,Artrite_Diagnostico,Doenca_Pulmonar_Obstrutiva_Cronica_Diagnostico,Diabetes_Tipo,Diabetes_Medicacao_Injetavel,Diabetes_Medicacao_Insulina_Parou_Ano,Diabetes_Medicacao_Insulina_Parou,Diabetes_Medicacao_Insulina_Tempo,Diabetes_Medicacao_Insulina,Diabetes_Medicacao_Pilula,Diabetes_Diagnostico,Gestacional_Diabetes_Diagnostico,Prediabetes_Diagnostico,Teve_cancer,Ermegencia_asma_12_meses,Asma_12_meses,Asma_Ativa,Teve_Asma,Teve_AVC,Teve_infarto,Teve_angina,Doenca_Cardiovascular_Diagnostico,Colesterol_Medicacao,Colesterol_12_meses,Colesterol_Diagnostico,Hipertensao_Medicacao,Hipertensao_12_meses,Hipertensao_Diagnostico_Dois_ou_mais_medicos,Hipertensao_Diagnostico,Satisfacao_Vida,Saude_Fisica,Indica_pessoa_é_o_Adulto_da_Amostra,Mes_Entrevista,Tipo_Registro,inputation number,fumante_media_cigarros,Peso_Amostral?,ID_Domicilio,nivel_pobreza
0,9,0,2,2,122,NaN,NaN,2,1,2,2,NaN,2,NaN,2.0,NaN,NaN,1,NaN,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,1,1,1,1,0.0,NaN,1.0,1,40.0,1.0,4.0,1.0,2.0,NaN,NaN,3.0,3.0,3,3,3,3,165,67,NaN,1,NaN,NaN,0,0,0,1.0,3,3,6,6,2,30.0,1.0,30.0,0,0,NaN,NaN,94,NaN,0,0,94,1,2,NaN,NaN,4.0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,3,3,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,5,5.0,1,1,2,0,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4,3,1,2024,1,49,NaN,1,2,2,2,2,NaN,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,2.0,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2,1,2.0,2,5.0,1.0,2.0,2.0,NaN,NaN,NaN,1,2,NaN,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,NaN,1.0,2.0,1,2,NaN,2,2,3,3,1,2,2,3,1,3,1,1,1,1,1,1,1,3,8,NaN,NaN,NaN,NaN,NaN,NaN,2,2,5,2,4,3,2,2,2,2,2,2,2,2,2,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2.0,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,3.0,23.0,1,3.0,1.0,2,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5,5,4,4,5,2,2,NaN,2,2.0,NaN,2,5,3.0,2,4,2,2.0,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,NaN,NaN,2,2.0,2.0,2.0,1.0,1,2,2,2,2,NaN,2,NaN,1.0,5,NaN,2.0,1.0,1.0,1.0,NaN,NaN,2.0,1,2,NaN,2,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2.0,NaN,1,2,2,2,2,2,2,2,2,2,2,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1.0,1.0,1,NaN,2,1,2,NaN,NaN,2,NaN,2,NaN,2,2,2,2,2,NaN,2,2,2,2,2,2,2,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,2,2,2,2,NaN,NaN,2,NaN,NaN,NaN,2,1,1,1,1,10,1,30,5780.565,H067658,2.82

In [4]:
#print("=== TABELA 4: PREVALÊNCIA DE MEDICAÇÃO POR GÊNERO (%) ===")
#display(pd.crosstab(df['SEXO_LABEL'], df['STATUS_MEDICACAO'], normalize='index').mul(100).round(2))

#print("\n=== TABELA 5: PREVALÊNCIA DE MEDICAÇÃO POR NÍVEL DE INSÔNIA (%) ===")
#display(pd.crosstab(df['INSÔNIA_INICIAL'], df['STATUS_MEDICACAO'], normalize='index').mul(100).round(2))

#print("\n=== TABELA 6: PREVALÊNCIA DE MEDICAÇÃO POR ESTRESSE COM CONTAS (%) ===")
#display(pd.crosstab(df['ESTRESSE_CONTAS'], df['STATUS_MEDICACAO'], normalize='index').mul(100).round(2))

#print("\n=== TABELA 7: PREVALÊNCIA DE MEDICAÇÃO POR FREQUÊNCIA DE SINTOMAS (%) ===")
#display(pd.crosstab(df['FREQ_ANSIEDADE'], df['STATUS_MEDICACAO'], normalize='index').mul(100).round(2))